use std::fs;
use std::path::Path;
use crate::ast::*;
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    let mut tools_json = Vec::new();
    for tool in &document.tools {
        tools_json.push(emit_tool_descriptor(tool));
    }
    for agent in &document.agents {
        tools_json.push(emit_agent_tool_descriptor(agent));
    }

    let mut schemas_json = Vec::new();
    for type_decl in &document.types {
        schemas_json.push(format!("  {}: {}", type_decl.name, emit_type_schema(&type_decl)));
    }

    let mut handlers = Vec::new();
    for tool in &document.tools {
        handlers.push(emit_handler(tool, document));
    }
    for agent in &document.agents {
        handlers.push(emit_agent_handler(agent, document));
    }

    let mut dispatch = Vec::new();
    for tool in &document.tools {
        dispatch.push(format!("  {}: handle{}", tool.name, tool.name));
    }
    for agent in &document.agents {
        dispatch.push(format!("  agent_{}: handleagent_{}", agent.name, agent.name));
    }

    let template = format!(
        r#"// generated/mcp-server.js
// AUTO-GENERATED by clawc build --lang opencode
// DO NOT EDIT — re-run clawc to regenerate

import {{ Server }} from "@modelcontextprotocol/sdk/server/index.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{
  CallToolRequestSchema,
  ListToolsRequestSchema,
}} from "@modelcontextprotocol/sdk/types.js";
import {{ fileURLToPath }} from "node:url";
import path from "node:path";
import fs from "node:fs/promises";

// ── Schema Validation ─────────────────────────────────────────────────────────

function validateOutput(value, schema, toolName) {{
  if (schema.type === "object") {{
    if (typeof value !== "object" || value === null) {{
      throw new Error(`${{toolName}}: expected object, got ${{typeof value}}`);
    }}
    for (const req of (schema.required ?? [])) {{
      if (!(req in value)) {{
        throw new Error(`${{toolName}}: missing required field "${{req}}"`);
      }}
    }}
  }} else if (schema.type === "array") {{
    if (!Array.isArray(value)) {{
      throw new Error(`${{toolName}}: expected array, got ${{typeof value}}`);
    }}
  }} else if (schema.type === "string" && typeof value !== "string") {{
    throw new Error(`${{toolName}}: expected string, got ${{typeof value}}`);
  }} else if (schema.type === "number" && typeof value !== "number") {{
    throw new Error(`${{toolName}}: expected number, got ${{typeof value}}`);
  }} else if (schema.type === "integer" && !Number.isInteger(value)) {{
    throw new Error(`${{toolName}}: expected integer, got ${{value}}`);
  }} else if (schema.type === "boolean" && typeof value !== "boolean") {{
    throw new Error(`${{toolName}}: expected boolean, got ${{typeof value}}`);
  }}
}}

// ── Tool Definitions ──────────────────────────────────────────────────────────

const TOOLS = [
{}
];

// ── Type Schemas (for output validation) ─────────────────────────────────────

const SCHEMAS = {{
{}
}};

// ── Tool Handlers ─────────────────────────────────────────────────────────────

{}

// ── Handler Dispatch ──────────────────────────────────────────────────────────

const HANDLERS = {{
{}
}};

// ── MCP Server Setup ──────────────────────────────────────────────────────────

const server = new Server(
  {{ name: "claw-tools", version: "1.0.0" }},
  {{ capabilities: {{ tools: {{}} }} }}
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({{
  tools: TOOLS
}}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {{
  const {{ name, arguments: args }} = request.params;
  const handler = HANDLERS[name];
  if (!handler) {{
    throw new Error(`Unknown tool: ${{name}}`);
  }}
  return handler(args ?? {{}});
}});

// ── Start ─────────────────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);
"#,
        tools_json.join(",\n"),
        schemas_json.join(",\n"),
        handlers.join("\n\n"),
        dispatch.join(",\n")
    );

    let output_path = project_root.join("generated").join("mcp-server.js");
    fs::write(output_path, template).map_err(|e| CompilerError::IoError {
        message: format!("failed to write mcp-server.js: {e}"),
        span: 0..0,
    })?;

    Ok(())
}

fn emit_tool_descriptor(tool: &ToolDecl) -> String {
    let mut props = Vec::new();
    let mut required = Vec::new();
    for arg in &tool.arguments {
        props.push(format!("      {}: {}", arg.name, data_type_to_json_schema(&arg.data_type)));
        required.push(format!("\"{}\"", arg.name));
    }

    format!(
        r#"  {{
    name: "{}",
    description: "{} tool",
    inputSchema: {{
      type: "object",
      properties: {{
{}
      }},
      required: [{}]
    }}
  }}"#,
        tool.name,
        tool.name,
        props.join(",\n"),
        required.join(", ")
    )
}

fn emit_type_schema(type_decl: &TypeDecl) -> String {
    let mut props = Vec::new();
    let mut required = Vec::new();
    for field in &type_decl.fields {
        props.push(format!("      {}: {}", field.name, data_type_to_json_schema(&field.data_type)));
        required.push(format!("\"{}\"", field.name));
    }

    format!(
        r#"{{
    type: "object",
    properties: {{
{}
    }},
    required: [{}]
  }}"#,
        props.join(",\n"),
        required.join(", ")
    )
}

fn emit_handler(tool: &ToolDecl, _document: &Document) -> String {
    let invoke_path = tool.invoke_path.as_deref().unwrap_or("scripts/stub");
    // Parse "module(X).function(Y)"
    // For now, assume it's like module("scripts/search").function("run")
    let parts: Vec<&str> = invoke_path.split('.').collect();
    let module_path = if parts.len() > 0 && parts[0].starts_with("module(\"") {
        let start = parts[0].find('"').unwrap() + 1;
        let end = parts[0].rfind('"').unwrap();
        &parts[0][start..end]
    } else {
        "scripts/stub"
    };

    let function_name = if parts.len() > 1 && parts[1].starts_with("function(\"") {
        let start = parts[1].find('"').unwrap() + 1;
        let end = parts[1].rfind('"').unwrap();
        &parts[1][start..end]
    } else {
        "run"
    };

    let args: Vec<_> = tool.arguments.iter().map(|a| a.name.as_str()).collect();
    let schema_ref = if let Some(rt) = &tool.return_type {
        match rt {
            DataType::Custom(name, _) => format!("SCHEMAS.{}", name),
            _ => format!("{{ type: \"{}\" }}", data_type_to_string(rt)),
        }
    } else {
        "null".to_owned()
    };

    format!(
        r#"async function handle{}(args) {{
  try {{
    const {{ {} }} = args;

    const modulePath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "../{}.js"
    );
    const real = await fs.realpath(modulePath);
    const wsRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
    const rel = path.relative(wsRoot, real);
    if (rel.startsWith("..") || path.isAbsolute(rel)) {{
      throw new Error(`Tool module resolves outside workspace: {}`);
    }}

    const mod = await import(new URL(real, "file://").href);
    const result = await mod.{}({});
    
    const schema = {};
    if (schema) {{
      validateOutput(result, schema, "{}");
    }}
    
    return {{ content: [{{ type: "text", text: typeof result === "string" ? result : JSON.stringify(result) }}] }};
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Error: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        tool.name,
        args.join(", "),
        module_path,
        module_path,
        function_name,
        args.join(", "),
        schema_ref,
        tool.name
    )
}

fn data_type_to_json_schema(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => r#"{ type: "string" }"#.to_owned(),
        DataType::Int(_) => r#"{ type: "integer" }"#.to_owned(),
        DataType::Float(_) => r#"{ type: "number" }"#.to_owned(),
        DataType::Boolean(_) => r#"{ type: "boolean" }"#.to_owned(),
        DataType::List(inner, _) => format!(r#"{{ type: "array", items: {} }}"#, data_type_to_json_schema(inner)),
        DataType::Custom(name, _) => format!(r##"{{ "$ref": "#/definitions/{}" }}"##, name),
    }
}

fn data_type_to_string(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => "string".to_owned(),
        DataType::Int(_) => "integer".to_owned(),
        DataType::Float(_) => "number".to_owned(),
        DataType::Boolean(_) => "boolean".to_owned(),
        DataType::List(..) => "array".to_owned(),
        DataType::Custom(name, _) => name.clone(),
    }
}
fn emit_agent_tool_descriptor(agent: &AgentDecl) -> String {
    let tools_list = agent.tools.join(", ");
    let system_prompt = agent.system_prompt.as_deref().unwrap_or("").replace('"', "\\\"").replace('\n', "\\n");
    format!(
        r#"  {{
    name: "agent_{}",
    description: "Run the {} agent. {}. Available tools: {}.",
    inputSchema: {{
      type: "object",
      properties: {{
        task: {{ type: "string", description: "The task for the {} agent to perform" }}
      }},
      required: ["task"]
    }}
  }}"#,
        agent.name, agent.name, system_prompt, tools_list, agent.name
    )
}

fn emit_agent_handler(agent: &AgentDecl, _document: &Document) -> String {
    let system_prompt = agent.system_prompt.as_deref().unwrap_or("").replace('"', "\\\"").replace('\n', "\\n");

    format!(
        r#"async function handleagent_{}(args) {{
  try {{
    const {{ task }} = args;
    const {{ execSync }} = await import("node:child_process");
    const {{ writeFileSync, unlinkSync }} = await import("node:fs");
    const {{ tmpdir }} = await import("node:os");
    const {{ join }} = await import("node:path");
    
    const systemPrompt = "{}";
    const tmpCtx = join(tmpdir(), `claw-agent-{}-${{Date.now()}}.md`);
    writeFileSync(tmpCtx, `# Agent: {}\n\n${{systemPrompt}}\n`);
    
    try {{
      const result = execSync(
        `opencode -p ${{JSON.stringify(task)}} -q`,
        {{
          env: {{ ...process.env, OPENCODE_CONTEXT: tmpCtx }},
          encoding: "utf8",
          timeout: 120000
        }}
      );
      return {{ content: [{{ type: "text", text: result }}] }};
    }} finally {{
      try {{ unlinkSync(tmpCtx); }} catch (_) {{}}
    }}
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Agent {} failed: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        agent.name, system_prompt, agent.name.to_lowercase(), agent.name, agent.name
    )
}
