use std::fs;
use std::path::Path;
use crate::ast::*;
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    let mut tools_json = Vec::new();
    for tool in &document.tools {
        tools_json.push(emit_tool_descriptor(tool));
    }
    for agent in &document.agents {
        tools_json.push(emit_agent_tool_descriptor(agent));
    }

    let mut schemas_json = Vec::new();
    for type_decl in &document.types {
        schemas_json.push(format!("  {}: {}", type_decl.name, emit_type_schema(&type_decl)));
    }

    let mut handlers = Vec::new();
    for tool in &document.tools {
        handlers.push(emit_handler(tool, document));
    }
    for agent in &document.agents {
        handlers.push(emit_agent_handler(agent, document));
    }

    let mut dispatch = Vec::new();
    for tool in &document.tools {
        dispatch.push(format!("  {}: handle{}", tool.name, tool.name));
    }
    for agent in &document.agents {
        dispatch.push(format!("  agent_{}: handleagent_{}", agent.name, agent.name));
    }

    let template = format!(
        r#"// generated/mcp-server.js
// AUTO-GENERATED by clawc build --lang opencode
// DO NOT EDIT — re-run clawc to regenerate

import {{ Server }} from "@modelcontextprotocol/sdk/server/index.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{
  CallToolRequestSchema,
  ListToolsRequestSchema,
}} from "@modelcontextprotocol/sdk/types.js";
import {{ fileURLToPath }} from "node:url";
import path from "node:path";
import fs from "node:fs/promises";

// ── Schema Validation ─────────────────────────────────────────────────────────

function validateOutput(value, schema, toolName) {{
  if (schema.type === "object") {{
    if (typeof value !== "object" || value === null) {{
      throw new Error(`${{toolName}}: expected object, got ${{typeof value}}`);
    }}
    for (const req of (schema.required ?? [])) {{
      if (!(req in value)) {{
        throw new Error(`${{toolName}}: missing required field "${{req}}"`);
      }}
    }}
  }} else if (schema.type === "array") {{
    if (!Array.isArray(value)) {{
      throw new Error(`${{toolName}}: expected array, got ${{typeof value}}`);
    }}
  }} else if (schema.type === "string" && typeof value !== "string") {{
    throw new Error(`${{toolName}}: expected string, got ${{typeof value}}`);
  }} else if (schema.type === "number" && typeof value !== "number") {{
    throw new Error(`${{toolName}}: expected number, got ${{typeof value}}`);
  }} else if (schema.type === "integer" && !Number.isInteger(value)) {{
    throw new Error(`${{toolName}}: expected integer, got ${{value}}`);
  }} else if (schema.type === "boolean" && typeof value !== "boolean") {{
    throw new Error(`${{toolName}}: expected boolean, got ${{typeof value}}`);
  }}
}}

// ── Tool Definitions ──────────────────────────────────────────────────────────

const TOOLS = [
{}
];

// ── Type Schemas (for output validation) ─────────────────────────────────────

const SCHEMAS = {{
{}
}};

// ── Tool Handlers ─────────────────────────────────────────────────────────────

{}

// ── Handler Dispatch ──────────────────────────────────────────────────────────

const HANDLERS = {{
{}
}};

// ── MCP Server Setup ──────────────────────────────────────────────────────────

const server = new Server(
  {{ name: "claw-tools", version: "1.0.0" }},
  {{ capabilities: {{ tools: {{}} }} }}
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({{
  tools: TOOLS
}}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {{
  const {{ name, arguments: args }} = request.params;
  const handler = HANDLERS[name];
  if (!handler) {{
    throw new Error(`Unknown tool: ${{name}}`);
  }}
  return handler(args ?? {{}});
}});

// ── Start ─────────────────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);
"#,
        tools_json.join(",\n"),
        schemas_json.join(",\n"),
        handlers.join("\n\n"),
        dispatch.join(",\n")
    );

    let output_path = project_root.join("generated").join("mcp-server.js");
    fs::write(output_path, template).map_err(|e| CompilerError::IoError {
        message: format!("failed to write mcp-server.js: {e}"),
        span: 0..0,
    })?;

    Ok(())
}

fn emit_tool_descriptor(tool: &ToolDecl) -> String {
    let mut props = Vec::new();
    let mut required = Vec::new();
    for arg in &tool.arguments {
        props.push(format!("      {}: {}", arg.name, data_type_to_json_schema(&arg.data_type)));
        required.push(format!("\"{}\"", arg.name));
    }

    format!(
        r#"  {{
    name: "{}",
    description: "{} tool",
    inputSchema: {{
      type: "object",
      properties: {{
{}
      }},
      required: [{}]
    }}
  }}"#,
        tool.name,
        tool.name,
        props.join(",\n"),
        required.join(", ")
    )
}

fn emit_type_schema(type_decl: &TypeDecl) -> String {
    let mut props = Vec::new();
    let mut required = Vec::new();
    for field in &type_decl.fields {
        props.push(format!("      {}: {}", field.name, data_type_to_json_schema_with_constraints(&field.data_type, &field.constraints)));
        required.push(format!("\"{}\"", field.name));
    }

    format!(
        r#"{{
    type: "object",
    properties: {{
{}
    }},
    required: [{}]
  }}"#,
        props.join(",\n"),
        required.join(", ")
    )
}

fn emit_handler(tool: &ToolDecl, _document: &Document) -> String {
    // Synthesized tools (using:) → route to generated/tools/<Name>.js
    // These are the purpose-built TypeScript files written by the synthesis loop.
    if tool.using.is_some() {
        return emit_synthesized_handler(tool);
    }

    let invoke_path = tool.invoke_path.as_deref().unwrap_or("scripts/stub");

    // baml(...) tools delegate to the BAML generated client, not a JS module
    if invoke_path.starts_with("baml(") {
        return emit_baml_handler(tool);
    }

    // Parse "module(X).function(Y)"
    let parts: Vec<&str> = invoke_path.split('.').collect();
    let module_path = if !parts.is_empty() && parts[0].starts_with("module(\"") {
        let start = parts[0].find('"').unwrap() + 1;
        let end = parts[0].rfind('"').unwrap();
        &parts[0][start..end]
    } else {
        "scripts/stub"
    };

    let function_name = if parts.len() > 1 && parts[1].starts_with("function(\"") {
        let start = parts[1].find('"').unwrap() + 1;
        let end = parts[1].rfind('"').unwrap();
        &parts[1][start..end]
    } else {
        "run"
    };

    let args: Vec<_> = tool.arguments.iter().map(|a| a.name.as_str()).collect();
    let schema_ref = if let Some(rt) = &tool.return_type {
        match rt {
            DataType::Custom(name, _) => format!("SCHEMAS.{}", name),
            _ => format!("{{ type: \"{}\" }}", data_type_to_string(rt)),
        }
    } else {
        "null".to_owned()
    };

    format!(
        r#"async function handle{}(args) {{
  try {{
    const {{ {} }} = args;

    const modulePath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "../{}.js"
    );
    const real = await fs.realpath(modulePath);
    const wsRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
    const rel = path.relative(wsRoot, real);
    if (rel.startsWith("..") || path.isAbsolute(rel)) {{
      throw new Error(`Tool module resolves outside workspace: {}`);
    }}

    const mod = await import(new URL(real, "file://").href);
    const result = await mod.{}({});

    const schema = {};
    if (schema) {{
      validateOutput(result, schema, "{}");
    }}

    return {{ content: [{{ type: "text", text: typeof result === "string" ? result : JSON.stringify(result) }}] }};
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Error: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        tool.name,
        args.join(", "),
        module_path,
        module_path,
        function_name,
        args.join(", "),
        schema_ref,
        tool.name
    )
}

/// Emit an MCP handler for a synthesis-path tool (`using:`).
/// Routes to `generated/tools/<Name>.js` — the LLM-written TypeScript compiled to JS.
/// Validates required secrets are present before calling.
fn emit_synthesized_handler(tool: &ToolDecl) -> String {
    let args: Vec<_> = tool.arguments.iter().map(|a| a.name.as_str()).collect();
    let args_obj = if args.is_empty() {
        "{}".to_owned()
    } else {
        format!("{{ {} }}", args.iter().map(|a| format!("{a}")).collect::<Vec<_>>().join(", "))
    };

    let schema_ref = if let Some(rt) = &tool.return_type {
        match rt {
            DataType::Custom(name, _) => format!("SCHEMAS.{}", name),
            _ => format!("{{ type: \"{}\" }}", data_type_to_string(rt)),
        }
    } else {
        "null".to_owned()
    };

    // Emit runtime secret checks — fail fast with a clear message rather than a confusing error
    // deep inside the synthesized code.
    let secret_checks = if tool.secrets.is_empty() {
        String::new()
    } else {
        let checks: Vec<String> = tool.secrets.iter().map(|key| {
            format!(
                "    if (!process.env[\"{key}\"]) {{\n      throw new Error('E-SEC01: required secret {key} not set — add it to your environment before running');\n    }}"
            )
        }).collect();
        checks.join("\n") + "\n"
    };

    // The synthesized file is TypeScript; at runtime we load the compiled JS.
    // `claw build` or `tsc` compiles generated/tools/<Name>.ts → generated/tools/<Name>.js.
    // If only the .ts exists (not yet compiled), we hint the user.
    format!(
        r#"async function handle{name}(args) {{
  try {{
    const {{ {arg_list} }} = args;

{secret_checks}    // Load the synthesized implementation.
    // Run `npx tsc generated/tools/{name}.ts --outDir generated/tools` to compile.
    const implPath = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "tools/{name}.js"
    );
    if (!await fs.access(implPath).then(() => true).catch(() => false)) {{
      throw new Error(
        'E-SYNTH01: generated/tools/{name}.js not found. ' +
        'Run `claw synthesize --tool {name}` then compile with tsc.'
      );
    }}
    const real = await fs.realpath(implPath);
    const wsRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
    const rel = path.relative(wsRoot, real);
    if (rel.startsWith("..") || path.isAbsolute(rel)) {{
      throw new Error('Tool module resolves outside workspace: {name}');
    }}

    const mod = await import(new URL(real, "file://").href);
    const result = await mod.{name}({args_obj});

    const schema = {schema_ref};
    if (schema) {{
      validateOutput(result, schema, "{name}");
    }}

    return {{ content: [{{ type: "text", text: typeof result === "string" ? result : JSON.stringify(result) }}] }};
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Error: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        name = tool.name,
        arg_list = args.join(", "),
        secret_checks = secret_checks,
        args_obj = args_obj,
        schema_ref = schema_ref,
    )
}

fn emit_baml_handler(tool: &ToolDecl) -> String {
    // Parse the BAML function name from invoke_path: baml("FunctionName") -> FunctionName
    let invoke_path = tool.invoke_path.as_deref().unwrap_or("");
    let baml_func_name = if invoke_path.starts_with("baml(") && invoke_path.ends_with(')') {
        let inside = &invoke_path[5..invoke_path.len() - 1];
        inside.trim_matches('"').to_owned()
    } else {
        tool.name.clone()
    };

    let args: Vec<_> = tool.arguments.iter().map(|a| a.name.as_str()).collect();
    let args_obj = if args.is_empty() {
        "{}".to_owned()
    } else {
        format!("{{ {} }}", args.join(", "))
    };
    let schema_ref = if let Some(rt) = &tool.return_type {
        match rt {
            DataType::Custom(name, _) => format!("SCHEMAS.{}", name),
            _ => format!("{{ type: \"{}\" }}", data_type_to_string(rt)),
        }
    } else {
        "null".to_owned()
    };

    format!(
        r#"async function handle{}(args) {{
  try {{
    const {{ {} }} = args;
    const {{ b }} = await import("../baml_client/index.js");
    const result = await b.{}({});
    const schema = {};
    if (schema) {{
      validateOutput(result, schema, "{}");
    }}
    return {{ content: [{{ type: "text", text: JSON.stringify(result) }}] }};
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Error: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        tool.name,
        args.join(", "),
        baml_func_name,
        args_obj,
        schema_ref,
        tool.name
    )
}

/// Emit a JSON Schema object for a type field that includes constraint keywords
/// (minimum, maximum, minLength, maxLength, pattern) from @min/@max/@regex annotations.
/// Spec 26 §3 — H-01 fix from spec 47.
fn data_type_to_json_schema_with_constraints(dt: &DataType, constraints: &[Constraint]) -> String {
    if constraints.is_empty() {
        return data_type_to_json_schema(dt);
    }

    let base_type = match dt {
        DataType::String(_)  => "string",
        DataType::Int(_)     => "integer",
        DataType::Float(_)   => "number",
        DataType::Boolean(_) => "boolean",
        DataType::List(..)   => return data_type_to_json_schema(dt), // list constraints not supported
        DataType::Custom(..) => return data_type_to_json_schema(dt),
    };

    let mut extras: Vec<String> = Vec::new();
    for c in constraints {
        let val = match &c.value.expr {
            Expr::IntLiteral(n)   => n.to_string(),
            Expr::FloatLiteral(f) => f.to_string(),
            Expr::StringLiteral(s) => format!("{s:?}"),
            _ => continue,
        };
        let keyword = match (c.name.as_str(), base_type) {
            ("min", "integer") | ("min", "number") => "minimum",
            ("max", "integer") | ("max", "number") => "maximum",
            ("min", "string")  => "minLength",
            ("max", "string")  => "maxLength",
            ("regex", "string") => "pattern",
            _ => continue,
        };
        extras.push(format!("{keyword}: {val}"));
    }

    if extras.is_empty() {
        return data_type_to_json_schema(dt);
    }

    format!("{{ type: \"{base_type}\", {} }}", extras.join(", "))
}

fn data_type_to_json_schema(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => r#"{ type: "string" }"#.to_owned(),
        DataType::Int(_) => r#"{ type: "integer" }"#.to_owned(),
        DataType::Float(_) => r#"{ type: "number" }"#.to_owned(),
        DataType::Boolean(_) => r#"{ type: "boolean" }"#.to_owned(),
        DataType::List(inner, _) => format!(r#"{{ type: "array", items: {} }}"#, data_type_to_json_schema(inner)),
        DataType::Custom(name, _) => format!(r##"{{ "$ref": "#/definitions/{}" }}"##, name),
    }
}

fn data_type_to_string(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => "string".to_owned(),
        DataType::Int(_) => "integer".to_owned(),
        DataType::Float(_) => "number".to_owned(),
        DataType::Boolean(_) => "boolean".to_owned(),
        DataType::List(..) => "array".to_owned(),
        DataType::Custom(name, _) => name.clone(),
    }
}
fn emit_agent_tool_descriptor(agent: &AgentDecl) -> String {
    let tools_list = agent.tools.join(", ");
    let system_prompt = agent.system_prompt.as_deref().unwrap_or("").replace('"', "\\\"").replace('\n', "\\n");
    format!(
        r#"  {{
    name: "agent_{}",
    description: "Run the {} agent. {}. Available tools: {}.",
    inputSchema: {{
      type: "object",
      properties: {{
        task: {{ type: "string", description: "The task for the {} agent to perform" }}
      }},
      required: ["task"]
    }}
  }}"#,
        agent.name, agent.name, system_prompt, tools_list, agent.name
    )
}

/// Collect all tool names for an agent, merging from parent via `extends` chain.
/// Spec 32 §21: merged tool list = parent.tools ∪ child.tools.
/// H-02 fix from spec 47.
fn resolve_agent_tools(agent: &AgentDecl, document: &Document) -> Vec<String> {
    let mut tools = agent.tools.clone();
    let mut current = agent;
    // Walk up the inheritance chain
    while let Some(parent_name) = &current.extends {
        if let Some(parent) = document.agents.iter().find(|a| &a.name == parent_name) {
            for t in &parent.tools {
                if !tools.contains(t) {
                    tools.push(t.clone());
                }
            }
            current = parent;
        } else {
            break;
        }
    }
    tools
}

/// Resolve the effective system_prompt for an agent, falling back to parent's if absent.
/// Spec 32 §21: child's prompt overrides; if absent, use parent's.
fn resolve_agent_system_prompt<'a>(agent: &'a AgentDecl, document: &'a Document) -> &'a str {
    if agent.system_prompt.is_some() {
        return agent.system_prompt.as_deref().unwrap_or("");
    }
    let mut current = agent;
    while let Some(parent_name) = &current.extends {
        if let Some(parent) = document.agents.iter().find(|a| &a.name == parent_name) {
            if parent.system_prompt.is_some() {
                return parent.system_prompt.as_deref().unwrap_or("");
            }
            current = parent;
        } else {
            break;
        }
    }
    ""
}

fn emit_agent_handler(agent: &AgentDecl, document: &Document) -> String {
    let system_prompt = resolve_agent_system_prompt(agent, document)
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n");

    // Resolve declared client → provider + model
    let (provider, model) = if let Some(client_name) = &agent.client {
        if let Some(client) = document.clients.iter().find(|c| &c.name == client_name) {
            (client.provider.clone(), client.model.clone())
        } else {
            ("anthropic".to_owned(), "claude-haiku-4-5-20251001".to_owned())
        }
    } else if let Some(client) = document.clients.first() {
        (client.provider.clone(), client.model.clone())
    } else {
        ("anthropic".to_owned(), "claude-haiku-4-5-20251001".to_owned())
    };

    let max_steps: i64 = agent.settings.entries.iter()
        .find(|e| e.name == "max_steps")
        .and_then(|e| if let crate::ast::SettingValue::Int(n) = e.value { Some(n) } else { None })
        .unwrap_or(10);

    let temperature: f64 = agent.settings.entries.iter()
        .find(|e| e.name == "temperature")
        .and_then(|e| match e.value {
            crate::ast::SettingValue::Float(f) => Some(f),
            crate::ast::SettingValue::Int(n) => Some(n as f64),
            _ => None,
        })
        .unwrap_or(1.0);

    // Merge tools from parent chain (H-02 fix)
    let effective_tools = resolve_agent_tools(agent, document);
    let agent_tools_filter = if effective_tools.is_empty() {
        "TOOLS.filter(t => !t.name.startsWith(\"agent_\"))".to_owned()
    } else {
        let names: Vec<String> = effective_tools.iter().map(|t| format!("\"{}\"", t)).collect();
        format!("TOOLS.filter(t => [{}].includes(t.name))", names.join(", "))
    };

    let is_local = provider == "local" || provider == "ollama";
    let model_str = model.trim_start_matches("local.").to_owned();

    if is_local {
        emit_agent_handler_ollama(agent, &system_prompt, &model_str, max_steps, temperature, &agent_tools_filter)
    } else {
        emit_agent_handler_anthropic(agent, &system_prompt, &model_str, max_steps, temperature, &agent_tools_filter)
    }
}

fn emit_agent_handler_anthropic(agent: &AgentDecl, system_prompt: &str, model: &str, max_steps: i64, temperature: f64, tools_filter: &str) -> String {
    format!(
        r#"async function handleagent_{}(args) {{
  try {{
    const {{ task }} = args;
    const Anthropic = (await import("@anthropic-ai/sdk")).default;
    const client = new Anthropic();

    const agentTools = {};
    const messages = [{{ role: "user", content: task }}];
    let steps = 0;

    while (steps < {}) {{
      steps++;
      const response = await client.messages.create({{
        model: "{}",
        system: "{}",
        messages,
        tools: agentTools.length > 0 ? agentTools.map(t => ({{
          name: t.name,
          description: t.description,
          input_schema: t.inputSchema,
        }})) : undefined,
        max_tokens: 4096,
        temperature: {},
      }});

      if (response.stop_reason === "end_turn") {{
        const text = response.content.find(b => b.type === "text")?.text ?? "";
        return {{ content: [{{ type: "text", text }}] }};
      }}

      if (response.stop_reason === "tool_use") {{
        const toolUseBlocks = response.content.filter(b => b.type === "tool_use");
        messages.push({{ role: "assistant", content: response.content }});
        const toolResults = [];
        for (const toolUse of toolUseBlocks) {{
          const handler = HANDLERS[toolUse.name];
          let resultContent;
          if (handler) {{
            const r = await handler(toolUse.input);
            resultContent = r.isError
              ? `Error: ${{r.content[0]?.text}}`
              : (r.content[0]?.text ?? "");
          }} else {{
            resultContent = `Error: unknown tool "${{toolUse.name}}"`;
          }}
          toolResults.push({{
            type: "tool_result",
            tool_use_id: toolUse.id,
            content: resultContent,
          }});
        }}
        messages.push({{ role: "user", content: toolResults }});
        continue;
      }}

      break;
    }}

    return {{
      content: [{{ type: "text", text: `Agent {} reached max_steps ({}) without finishing.` }}],
      isError: true,
    }};
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Agent {} failed: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        agent.name,
        tools_filter,
        max_steps,
        model,
        system_prompt,
        temperature,
        agent.name, max_steps,
        agent.name
    )
}

fn emit_agent_handler_ollama(agent: &AgentDecl, system_prompt: &str, model: &str, max_steps: i64, temperature: f64, tools_filter: &str) -> String {
    format!(
        r#"async function handleagent_{}(args) {{
  try {{
    const {{ task }} = args;
    const agentTools = {};
    const messages = [
      {{ role: "system", content: "{}" }},
      {{ role: "user", content: task }}
    ];
    let steps = 0;

    while (steps < {}) {{
      steps++;
      const ollamaRes = await fetch("http://localhost:11434/v1/chat/completions", {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{
          model: "{}",
          messages,
          tools: agentTools.length > 0 ? agentTools.map(t => ({{
            type: "function",
            function: {{ name: t.name, description: t.description, parameters: t.inputSchema }},
          }})) : undefined,
          stream: false,
          temperature: {},
        }}),
      }});
      const data = await ollamaRes.json();
      const choice = data.choices?.[0];
      if (!choice) break;

      if (choice.finish_reason === "stop" || choice.finish_reason === "length") {{
        const text = choice.message?.content ?? "";
        return {{ content: [{{ type: "text", text }}] }};
      }}

      if (choice.finish_reason === "tool_calls") {{
        const toolCalls = choice.message?.tool_calls ?? [];
        messages.push({{ role: "assistant", content: choice.message?.content ?? null, tool_calls: toolCalls }});
        for (const tc of toolCalls) {{
          const handler = HANDLERS[tc.function.name];
          let resultContent;
          try {{
            const tcArgs = typeof tc.function.arguments === "string"
              ? JSON.parse(tc.function.arguments)
              : tc.function.arguments;
            if (handler) {{
              const r = await handler(tcArgs);
              resultContent = r.isError ? `Error: ${{r.content[0]?.text}}` : (r.content[0]?.text ?? "");
            }} else {{
              resultContent = `Error: unknown tool "${{tc.function.name}}"`;
            }}
          }} catch (e) {{
            resultContent = `Error: ${{e.message}}`;
          }}
          messages.push({{ role: "tool", tool_call_id: tc.id, content: resultContent }});
        }}
        continue;
      }}

      break;
    }}

    return {{
      content: [{{ type: "text", text: `Agent {} reached max_steps ({}) without finishing.` }}],
      isError: true,
    }};
  }} catch (err) {{
    return {{
      content: [{{ type: "text", text: `Agent {} failed: ${{err.message}}` }}],
      isError: true
    }};
  }}
}}"#,
        agent.name,
        tools_filter,
        system_prompt,
        max_steps,
        model,
        temperature,
        agent.name, max_steps,
        agent.name
    )
}
