// src/codegen/python.rs
// Generates generated/claw/__init__.py — a self-contained BAML-style Python client.
// No claw_sdk dependency. Only pip deps: pydantic, httpx.
// Each workflow compiles to a typed importable async function.
// Supports artifact placement: workflow { artifact { format = "..." path = "..." } }

use std::collections::HashSet;

use crate::ast::{
    AgentDecl, Block, Constraint, DataType, Document, Expr, SettingValue, SpannedExpr, Statement,
    ToolDecl, TypeDecl, TypeField,
};
use crate::errors::{CompilerError, CompilerResult};

pub(super) fn generate(document: &Document) -> CompilerResult<String> {
    let mut out = String::new();

    // 1. File header + imports
    out.push_str(HEADER);
    out.push_str("\n\n");

    // 2. Pydantic models
    for t in &document.types {
        out.push_str(&render_model(t)?);
        out.push_str("\n\n");
    }

    // 3. Tool handlers
    out.push_str(&emit_tool_handlers(document));

    // 4. Agent runners
    out.push_str(&emit_agent_runners(document));

    // 5. Workflow functions
    for wf in &document.workflows {
        out.push_str(&render_workflow(wf, document)?);
        out.push_str("\n\n");
    }

    // 6. CLI entry
    out.push_str(&emit_cli_entry(document));

    Ok(out)
}

// ─── Header ───────────────────────────────────────────────────────────────────

const HEADER: &str = r#"# generated/claw/__init__.py
# AUTO-GENERATED by claw build --lang python — DO NOT EDIT
# Run:    python generated/claw/__init__.py <WorkflowName> --arg key=value
# Import: from generated.claw import find_info
# Deps:   pip install pydantic httpx
from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path
from typing import Any

# Locate project root by walking up from this file until we find a claw.json
# or Cargo.toml marker. This is robust regardless of how deep claw build wrote
# the generated file (e.g. examples/generated/claw/ vs generated/claw/).
def _find_project_root() -> str:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / "claw.json").exists() or (p / "Cargo.toml").exists():
            return str(p)
        p = p.parent
    # Fallback: four levels up (the original assumption) if no marker found
    return str(Path(__file__).resolve().parent.parent.parent.parent)

_PROJECT_ROOT = _find_project_root()
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

import httpx
from pydantic import BaseModel, Field"#;

// ─── Pydantic Models ──────────────────────────────────────────────────────────

fn render_model(declaration: &TypeDecl) -> CompilerResult<String> {
    let fields = declaration
        .fields
        .iter()
        .map(render_model_field)
        .collect::<CompilerResult<Vec<_>>>()?
        .join("\n");
    Ok(format!("class {}(BaseModel):\n{}", declaration.name, fields))
}

fn render_model_field(field: &TypeField) -> CompilerResult<String> {
    let py_type = render_python_type(&field.data_type);
    let config = render_field_config(&field.data_type, &field.constraints)?;
    Ok(match config {
        Some(cfg) => format!("    {}: {} = Field({})", field.name, py_type, cfg),
        None => format!("    {}: {}", field.name, py_type),
    })
}

// ─── Tool Handlers ────────────────────────────────────────────────────────────

fn emit_tool_handlers(document: &Document) -> String {
    let mut handlers: Vec<String> = Vec::new();
    let mut cases: Vec<String> = Vec::new();

    for tool in &document.tools {
        let handler = emit_tool_handler(tool);
        handlers.push(handler);
        cases.push(format!(
            "    if name == \"{name}\":\n        return await _call_tool_{name}(input)",
            name = tool.name,
        ));
    }

    let dispatch = if cases.is_empty() {
        r#"async def _call_tool(name: str, input: dict) -> Any:
    raise RuntimeError(f"unknown tool: {name}")"#
            .to_owned()
    } else {
        format!(
            r#"async def _call_tool(name: str, input: dict) -> Any:
{}
    raise RuntimeError(f"unknown tool: {{name}}")"#,
            cases.join("\n")
        )
    };

    if handlers.is_empty() {
        format!("{}\n\n", dispatch)
    } else {
        format!("{}\n\n{}\n\n", handlers.join("\n\n"), dispatch)
    }
}

fn emit_tool_handler(tool: &ToolDecl) -> String {
    let args_annotation = if tool.arguments.is_empty() {
        String::new()
    } else {
        tool.arguments
            .iter()
            .map(|a| format!("{}: {}", a.name, render_python_type(&a.data_type)))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let comment = if args_annotation.is_empty() {
        String::new()
    } else {
        format!("  # {{{args_annotation}}}")
    };

    let body = if let Some(invoke) = &tool.invoke_path {
        if invoke.starts_with("module(") {
            emit_module_tool_body(tool, invoke)
        } else {
            format!("    raise RuntimeError(\"tool '{}': unsupported invoke path\")", tool.name)
        }
    } else {
        format!("    raise RuntimeError(\"tool '{}': no handler configured\")", tool.name)
    };

    format!(
        "async def _call_tool_{name}(input: dict) -> Any:{comment}\n{body}",
        name = tool.name,
        comment = comment,
        body = body,
    )
}

fn emit_module_tool_body(tool: &ToolDecl, invoke_path: &str) -> String {
    // Parse: module("scripts/search").function("run")
    let parts: Vec<&str> = invoke_path.splitn(2, ").function(").collect();
    let module_path = if parts[0].len() > 8 {
        let s = &parts[0][8..];
        s[..s.rfind('"').unwrap_or(s.len())].replace('/', ".")
    } else {
        "scripts.stub".to_owned()
    };
    let fn_name = if parts.len() > 1 && parts[1].len() > 1 {
        let s = &parts[1][1..];
        s[..s.rfind('"').unwrap_or(s.len())].to_owned()
    } else {
        "run".to_owned()
    };

    let arg_names: Vec<&str> = tool.arguments.iter().map(|a| a.name.as_str()).collect();
    let arg_extract: Vec<String> = arg_names
        .iter()
        .map(|n| format!("    {} = input.get(\"{}\")", n, n))
        .collect();
    let call_args = arg_names.join(", ");

    format!(
        "    import importlib\n{}\n    mod = importlib.import_module(\"{}\")\n    return await asyncio.get_event_loop().run_in_executor(None, mod.{}, {})",
        arg_extract.join("\n"),
        module_path,
        fn_name,
        call_args,
    )
}

// ─── Agent Runners ────────────────────────────────────────────────────────────

fn emit_agent_runners(document: &Document) -> String {
    let mut out = String::new();
    for agent in &document.agents {
        let (provider, model) = resolve_client(agent, document);
        let is_local = provider == "local" || provider == "ollama";
        let model_str = model.trim_start_matches("local.").to_owned();

        let system_prompt = agent
            .system_prompt
            .as_deref()
            .unwrap_or("")
            .replace('\\', "\\\\")
            .replace('\'', "\\'")
            .replace('\n', "\\n");

        let max_steps: i64 = agent
            .settings
            .entries
            .iter()
            .find(|e| e.name == "max_steps")
            .and_then(|e| {
                if let SettingValue::Int(n) = e.value {
                    Some(n)
                } else {
                    None
                }
            })
            .unwrap_or(10);

        let temperature: f64 = agent
            .settings
            .entries
            .iter()
            .find(|e| e.name == "temperature")
            .and_then(|e| match e.value {
                SettingValue::Float(f) => Some(f),
                SettingValue::Int(n) => Some(n as f64),
                _ => None,
            })
            .unwrap_or(1.0);

        let tools_filter = emit_py_tools_array(document, if agent.tools.is_empty() { None } else { Some(&agent.tools) });

        let fn_name = format!("_run_agent_{}", to_snake_case(&agent.name));

        let runner = if is_local {
            emit_py_ollama_runner(&fn_name, &system_prompt, &model_str, max_steps, temperature, &tools_filter)
        } else {
            emit_py_anthropic_runner(&fn_name, &system_prompt, &model_str, max_steps, temperature, &tools_filter)
        };

        out.push_str(&runner);
        out.push_str("\n\n");
    }
    out
}

fn emit_py_tools_array(document: &Document, filter: Option<&[String]>) -> String {
    let tools: Vec<_> = document
        .tools
        .iter()
        .filter(|t| filter.map(|f| f.contains(&t.name)).unwrap_or(true))
        .collect();

    if tools.is_empty() {
        return "[]".to_owned();
    }

    let entries: Vec<String> = tools
        .iter()
        .map(|tool| {
            let props: Vec<String> = tool
                .arguments
                .iter()
                .map(|a| format!("                    \"{}\": {{\"type\": \"{}\"}}", a.name, py_json_type(&a.data_type)))
                .collect();
            let required: Vec<String> = tool.arguments.iter().map(|a| format!("\"{}\"", a.name)).collect();
            format!(
                r#"    {{
        "name": "{name}",
        "description": "Tool {name}",
        "input_schema": {{
            "type": "object",
            "properties": {{
{props}
            }},
            "required": [{req}]
        }}
    }}"#,
                name = tool.name,
                props = props.join(",\n"),
                req = required.join(", "),
            )
        })
        .collect();

    format!("[\n{}\n]", entries.join(",\n"))
}

fn py_json_type(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => "string".to_owned(),
        DataType::Int(_) => "integer".to_owned(),
        DataType::Float(_) => "number".to_owned(),
        DataType::Boolean(_) => "boolean".to_owned(),
        DataType::List(_, _) => "array".to_owned(),
        DataType::Custom(_, _) => "object".to_owned(),
    }
}

fn emit_py_anthropic_runner(
    fn_name: &str,
    system_prompt: &str,
    model: &str,
    max_steps: i64,
    temperature: f64,
    tools_array: &str,
) -> String {
    format!(
        r#"async def {fn_name}(task: str) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not set\n  export ANTHROPIC_API_KEY=sk-ant-...")
    agent_tools = {tools_array}
    messages: list[dict] = [{{"role": "user", "content": task}}]
    steps = 0

    async with httpx.AsyncClient(timeout=120) as client:
        while steps < {max_steps}:
            steps += 1
            payload: dict = {{
                "model": "{model}",
                "system": "{system_prompt}",
                "messages": messages,
                "max_tokens": 4096,
                "temperature": {temperature},
            }}
            if agent_tools:
                payload["tools"] = agent_tools
            resp = await client.post(
                "https://api.anthropic.com/v1/messages",
                headers={{
                    "x-api-key": api_key,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                }},
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()

            if data.get("stop_reason") == "end_turn":
                text_blocks = [b for b in data.get("content", []) if b.get("type") == "text"]
                return "".join(b.get("text", "") for b in text_blocks)

            if data.get("stop_reason") == "tool_use":
                tool_use_blocks = [b for b in data.get("content", []) if b.get("type") == "tool_use"]
                messages.append({{"role": "assistant", "content": data["content"]}})
                tool_results = []
                for tu in tool_use_blocks:
                    try:
                        result_content = json.dumps(await _call_tool(tu["name"], tu.get("input", {{}})))
                    except Exception as e:
                        result_content = f"Error: {{e}}"
                    tool_results.append({{"type": "tool_result", "tool_use_id": tu["id"], "content": result_content}})
                messages.append({{"role": "user", "content": tool_results}})
                continue
            break

    return f"Agent {fn_name} reached max_steps ({max_steps}) without finishing."
"#,
        fn_name = fn_name,
        tools_array = tools_array,
        max_steps = max_steps,
        model = model,
        system_prompt = system_prompt,
        temperature = temperature,
    )
}

fn emit_py_ollama_runner(
    fn_name: &str,
    system_prompt: &str,
    model: &str,
    max_steps: i64,
    temperature: f64,
    tools_array: &str,
) -> String {
    format!(
        r#"async def {fn_name}(task: str) -> str:
    host = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
    agent_tools = {tools_array}
    messages: list[dict] = [
        {{"role": "system", "content": "{system_prompt}"}},
        {{"role": "user", "content": task}},
    ]
    steps = 0

    async with httpx.AsyncClient(timeout=120) as client:
        while steps < {max_steps}:
            steps += 1
            payload: dict = {{
                "model": "{model}",
                "messages": messages,
                "stream": False,
                "temperature": {temperature},
            }}
            if agent_tools:
                payload["tools"] = [
                    {{"type": "function", "function": {{"name": t["name"], "description": t["description"], "parameters": t["input_schema"]}}}}
                    for t in agent_tools
                ]
            resp = await client.post(
                f"{{host}}/v1/chat/completions",
                headers={{"content-type": "application/json"}},
                json=payload,
            )
            resp.raise_for_status()
            data = resp.json()
            choices = data.get("choices", [])
            if not choices:
                break
            choice = choices[0]

            if choice.get("finish_reason") in ("stop", "length"):
                return choice.get("message", {{}}).get("content") or ""

            if choice.get("finish_reason") == "tool_calls":
                tool_calls = choice.get("message", {{}}).get("tool_calls", [])
                messages.append({{"role": "assistant", "content": choice.get("message", {{}}).get("content"), "tool_calls": tool_calls}})
                for tc in tool_calls:
                    try:
                        fn_args = tc["function"].get("arguments", {{}})
                        if isinstance(fn_args, str):
                            fn_args = json.loads(fn_args)
                        result_content = json.dumps(await _call_tool(tc["function"]["name"], fn_args))
                    except Exception as e:
                        result_content = f"Error: {{e}}"
                    messages.append({{"role": "tool", "tool_call_id": tc["id"], "content": result_content}})
                continue
            break

    return f"Agent {fn_name} reached max_steps ({max_steps}) without finishing."
"#,
        fn_name = fn_name,
        tools_array = tools_array,
        max_steps = max_steps,
        system_prompt = system_prompt,
        model = model,
        temperature = temperature,
    )
}

fn resolve_client(agent: &AgentDecl, document: &Document) -> (String, String) {
    if let Some(client_name) = &agent.client {
        if let Some(c) = document.clients.iter().find(|c| &c.name == client_name) {
            return (c.provider.clone(), c.model.clone());
        }
    }
    if let Some(c) = document.clients.first() {
        return (c.provider.clone(), c.model.clone());
    }
    ("anthropic".to_owned(), "claude-haiku-4-5-20251001".to_owned())
}

// ─── Workflow Functions ───────────────────────────────────────────────────────

fn render_workflow(
    wf: &crate::ast::WorkflowDecl,
    document: &Document,
) -> CompilerResult<String> {
    let params = if wf.arguments.is_empty() {
        String::new()
    } else {
        let parts: Vec<String> = wf
            .arguments
            .iter()
            .map(|a| format!("{}: {}", a.name, render_python_type(&a.data_type)))
            .collect();
        format!(", {}", parts.join(", "))
    };

    let return_type = wf
        .return_type
        .as_ref()
        .map(render_python_type)
        .unwrap_or_else(|| "Any".to_owned());

    let wf_arg_names: HashSet<String> = wf.arguments.iter().map(|a| a.name.clone()).collect();
    let body = render_workflow_body(&wf.body, &wf_arg_names, document)?;

    // Artifact saving block
    let artifact_block = if let Some(artifact) = &wf.artifact {
        let expanded_path = py_expand_path(&artifact.path, &wf_arg_names);
        if artifact.format == "image" {
            // Image: result must have a `path` field (local file from fetch_image)
            // Copy the file to the declared artifact path instead of writing text.
            format!(
                r#"    # artifact: copy image to declared path
    _src_path = Path(getattr(result, 'path', '') or (result.get('path', '') if isinstance(result, dict) else ''))
    _artifact_path = Path(os.path.expanduser(f"{expanded_path}")).resolve()
    _artifact_path.parent.mkdir(parents=True, exist_ok=True)
    if _src_path and _src_path.exists() and _src_path != _artifact_path:
        import shutil
        shutil.copy2(_src_path, _artifact_path)
    elif not _src_path or not _src_path.exists():
        _artifact_path.write_bytes(b'')
    print(f"[claw] artifact saved → {{_artifact_path}}", file=sys.stderr)
"#,
            )
        } else {
            let serialize = match artifact.format.as_str() {
                "json" => "json.dumps(result.model_dump() if hasattr(result, 'model_dump') else result, indent=2)".to_owned(),
                "markdown" | "text" => "getattr(result, 'content', None) or str(result)".to_owned(),
                "html" => "getattr(result, 'content', None) or f'<pre>{result}</pre>'".to_owned(),
                _ => "json.dumps(result.model_dump() if hasattr(result, 'model_dump') else result, indent=2)".to_owned(),
            };
            format!(
                r#"    # artifact: save output to file
    _artifact_path = Path(os.path.expanduser(f"{expanded_path}")).resolve()
    _artifact_path.parent.mkdir(parents=True, exist_ok=True)
    _artifact_path.write_text({serialize})
    print(f"[claw] artifact saved → {{_artifact_path}}", file=sys.stderr)
"#,
            )
        }
    } else {
        String::new()
    };

    Ok(format!(
        "async def {fn_name}(*{params}) -> {ret}:\n{body}{artifact}    return result\n",
        fn_name = to_snake_case(&wf.name),
        params = params,
        ret = return_type,
        body = body,
        artifact = artifact_block,
    ))
}

fn render_workflow_body(
    block: &Block,
    wf_arg_names: &HashSet<String>,
    document: &Document,
) -> CompilerResult<String> {
    let mut lines: Vec<String> = Vec::new();
    let mut local_vars: HashSet<String> = HashSet::new();

    for stmt in &block.statements {
        let compiled = compile_py_statement(stmt, wf_arg_names, &local_vars, document)?;
        lines.push(compiled);
        if let Statement::LetDecl { name, .. } = stmt {
            local_vars.insert(name.clone());
        }
    }

    if lines.is_empty() {
        lines.push("    pass".to_owned());
    }

    Ok(lines.join("\n"))
}

fn compile_py_statement(
    stmt: &Statement,
    wf_arg_names: &HashSet<String>,
    _local_vars: &HashSet<String>,
    _document: &Document,
) -> CompilerResult<String> {
    match stmt {
        Statement::LetDecl { name, value, explicit_type, .. } => match &value.expr {
            Expr::ExecuteRun { agent_name, kwargs, require_type } => {
                let task_py = extract_task_py(kwargs, wf_arg_names);
                Ok(emit_py_execute_and_bind(name, agent_name, &task_py, require_type.as_ref()))
            }
            Expr::DirectToolCall { tool_name, args } => {
                Ok(emit_py_direct_tool_call(name, tool_name, args, explicit_type.as_ref(), wf_arg_names))
            }
            _ => {
                let val = expr_to_py(&value.expr, wf_arg_names);
                Ok(format!("    {name} = {val}\n"))
            }
        },

        Statement::ExecuteRun { agent_name, kwargs, require_type, .. } => {
            let task_py = extract_task_py(kwargs, wf_arg_names);
            Ok(emit_py_execute_and_bind("_", agent_name, &task_py, require_type.as_ref()))
        }

        Statement::Return { value, .. } => match &value.expr {
            Expr::Identifier(name) => Ok(format!("    result = {name}\n")),
            Expr::ExecuteRun { agent_name, kwargs, require_type } => {
                let task_py = extract_task_py(kwargs, wf_arg_names);
                Ok(emit_py_execute_and_bind("result", agent_name, &task_py, require_type.as_ref()))
            }
            Expr::DirectToolCall { tool_name, args } => {
                Ok(emit_py_direct_tool_call("result", tool_name, args, None, wf_arg_names))
            }
            other => {
                let val = expr_to_py(other, wf_arg_names);
                Ok(format!("    result = {val}\n"))
            }
        },

        Statement::Reason { using_agent, input, goal, bind, output_type, on_fail, .. } => {
            let target = if bind == "_" { "result".to_owned() } else { bind.clone() };
            let escaped_goal = goal.replace('"', "\\\"");
            let task_py = if input.is_empty() || input == "_" {
                format!("\"{}\"", escaped_goal)
            } else {
                format!(
                    "f\"Context:\\n{{json.dumps({input} if isinstance({input}, dict) else ({input}.model_dump() if hasattr({input}, 'model_dump') else str({input})), indent=2)}}\\n\\nGoal: {escaped_goal}\""
                )
            };

            let base_call = emit_py_execute_and_bind(&target, using_agent, &task_py, Some(output_type));

            match on_fail {
                Some(crate::ast::OnFailStrategy::Retry { max }) => {
                    // Wrap in a retry loop. The agent re-runs up to `max` times if it judges the
                    // output as not meeting the goal.
                    let mut out = String::new();
                    out.push_str(&format!("    for _attempt in range({max}):\n"));
                    // Indent base_call by 4 more spaces (one extra level)
                    for line in base_call.lines() {
                        out.push_str("    ");
                        out.push_str(line);
                        out.push('\n');
                    }
                    out.push_str(&format!(
                        "        _ok = await _run_agent_{agent}(f\"Judge whether this meets the goal: {{json.dumps({target} if isinstance({target}, dict) else ({target}.model_dump() if hasattr({target}, 'model_dump') else str({target})), indent=2)}}\\n\\nGoal: {escaped_goal}\\nReply with only: YES or NO\")\n",
                        agent = to_snake_case(using_agent),
                    ));
                    out.push_str(&format!(
                        "        if str(_ok).strip().upper().startswith('YES'):\n            break\n"
                    ));
                    out.push_str(&format!(
                        "    else:\n        raise RuntimeError(f\"reason: goal not achieved after {max} attempts: {escaped_goal}\")\n"
                    ));
                    Ok(out)
                }
                Some(crate::ast::OnFailStrategy::ReSynthesize) => {
                    // Run once; if rejected, trigger re-synthesis (via subprocess) and retry.
                    let mut out = base_call.clone();
                    out.push_str(&format!(
                        "    _ok = await _run_agent_{agent}(f\"Judge: {{json.dumps({target} if isinstance({target}, dict) else ({target}.model_dump() if hasattr({target}, 'model_dump') else str({target})), indent=2)}}\\n\\nGoal: {escaped_goal}\\nReply with only: YES or NO\")\n",
                        agent = to_snake_case(using_agent),
                    ));
                    out.push_str("    if not str(_ok).strip().upper().startswith('YES'):\n");
                    out.push_str("        import subprocess\n");
                    out.push_str(&format!(
                        "        subprocess.run([\"claw\", \"synthesize\"], check=False)\n"
                    ));
                    for line in base_call.lines() {
                        out.push_str("        ");
                        out.push_str(line.trim_start_matches("    "));
                        out.push('\n');
                    }
                    Ok(out)
                }
                None => Ok(base_call),
            }
        }

        _ => Ok("    # [unsupported statement in --lang python v1]\n".to_owned()),
    }
}

fn emit_py_execute_and_bind(
    bind: &str,
    agent_name: &str,
    task_py: &str,
    require_type: Option<&DataType>,
) -> String {
    let raw_var = if bind == "_" {
        "_raw_output".to_owned()
    } else {
        format!("_raw_{bind}")
    };

    let call_line = format!(
        "    {raw_var} = await _run_agent_{agent}({task})\n",
        raw_var = raw_var,
        agent = to_snake_case(agent_name),
        task = task_py,
    );

    match require_type {
        Some(DataType::Custom(type_name, _)) => {
            let parsed = format!(
                "    try:\n        {bind} = {type_name}.model_validate(json.loads({raw_var}) if isinstance({raw_var}, str) else {raw_var})\n    except Exception as _e:\n        raise RuntimeError(f\"type validation failed for {type_name}\\n  got: {{{raw_var}}}\") from _e\n",
                bind = bind,
                type_name = type_name,
                raw_var = raw_var,
            );
            format!("{call_line}{parsed}")
        }
        _ => {
            if bind == "_" {
                call_line
            } else {
                format!("{call_line}    {bind} = {raw_var}\n")
            }
        }
    }
}

/// Emits a direct (no-LLM) tool call: `bind = await _call_tool_X({"arg": val, ...})`
/// followed by optional Pydantic model_validate if the explicit type is a custom type.
fn emit_py_direct_tool_call(
    bind: &str,
    tool_name: &str,
    args: &[(String, SpannedExpr)],
    explicit_type: Option<&DataType>,
    wf_arg_names: &HashSet<String>,
) -> String {
    let dict_entries: Vec<String> = args
        .iter()
        .map(|(k, v)| format!("\"{k}\": {}", expr_to_py(&v.expr, wf_arg_names)))
        .collect();
    let dict_py = format!("{{{}}}", dict_entries.join(", "));

    let raw_var = format!("_raw_{bind}");
    let call_line = format!("    {raw_var} = await _call_tool_{tool_name}({dict_py})\n");

    match explicit_type {
        Some(DataType::Custom(type_name, _)) => {
            let validate = format!(
                "    try:\n        {bind} = {type_name}.model_validate(json.loads({raw_var}) if isinstance({raw_var}, str) else {raw_var})\n    except Exception as _e:\n        raise RuntimeError(f\"type validation failed for {type_name}\\n  got: {{{raw_var}}}\") from _e\n",
                bind = bind,
                type_name = type_name,
                raw_var = raw_var,
            );
            format!("{call_line}{validate}")
        }
        _ => format!("{call_line}    {bind} = {raw_var}\n"),
    }
}

fn extract_task_py(kwargs: &[(String, SpannedExpr)], wf_arg_names: &HashSet<String>) -> String {
    for (key, val) in kwargs {
        if key == "task" {
            return expr_to_py_task(&val.expr, wf_arg_names);
        }
    }
    "\"<no task>\"".to_owned()
}

fn expr_to_py_task(expr: &Expr, wf_arg_names: &HashSet<String>) -> String {
    match expr {
        Expr::Identifier(name) => {
            if wf_arg_names.contains(name.as_str()) {
                name.clone() // Python variables are already in scope
            } else {
                name.clone()
            }
        }
        Expr::StringLiteral(s) => {
            // Convert to Python f-string, replacing ${name} → {name}
            let inner = claw_template_to_python_fstring(s, wf_arg_names);
            format!("f\"{inner}\"")
        }
        _ => "\"\"".to_owned(),
    }
}

fn claw_template_to_python_fstring(s: &str, _wf_arg_names: &HashSet<String>) -> String {
    // Replace ${varname} with {varname} for Python f-string
    let mut result = String::with_capacity(s.len() + 4);
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '$' && chars.peek() == Some(&'{') {
            chars.next(); // consume '{'
            let mut var_name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
                var_name.push(c2);
            }
            result.push('{');
            result.push_str(&var_name);
            result.push('}');
        } else if c == '"' {
            result.push_str("\\\"");
        } else if c == '{' {
            result.push_str("{{"); // escape literal braces in f-string
        } else if c == '}' {
            result.push_str("}}");
        } else {
            result.push(c);
        }
    }
    result
}

fn py_expand_path(path: &str, wf_arg_names: &HashSet<String>) -> String {
    // Convert `~/Desktop/${topic}.json` → `~/Desktop/{topic}.json` for Python f-string
    claw_template_to_python_fstring(path, wf_arg_names)
}

fn expr_to_py(expr: &Expr, wf_arg_names: &HashSet<String>) -> String {
    match expr {
        Expr::StringLiteral(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Expr::IntLiteral(n) => n.to_string(),
        Expr::FloatLiteral(f) => f.to_string(),
        Expr::BoolLiteral(b) => if *b { "True".to_owned() } else { "False".to_owned() },
        Expr::Identifier(name) => name.clone(),
        Expr::MemberAccess(target, field) => {
            let target_py = expr_to_py(&target.expr, wf_arg_names);
            format!("{target_py}.{field}")
        }
        // DirectToolCall in expression position — not awaitable inline, emit as None with comment
        Expr::DirectToolCall { tool_name, .. } => {
            format!("None  # call {tool_name}(...) must be used in a let binding")
        }
        _ => "None".to_owned(),
    }
}

// ─── CLI Entry ────────────────────────────────────────────────────────────────

fn emit_cli_entry(document: &Document) -> String {
    let workflow_list: Vec<String> = document
        .workflows
        .iter()
        .map(|wf| {
            let req_args: Vec<String> = wf
                .arguments
                .iter()
                .map(|a| format!("\"{}\"", a.name))
                .collect();
            let return_type = match &wf.return_type {
                Some(DataType::Custom(name, _)) => format!("\"{}\"", name),
                Some(_) => "\"unknown\"".to_owned(),
                None => "None".to_owned(),
            };
            format!(
                "    {{\"name\": \"{name}\", \"requiredArgs\": [{args}], \"returnType\": {ret}}}",
                name = wf.name,
                args = req_args.join(", "),
                ret = return_type,
            )
        })
        .collect();

    let cases: Vec<String> = document
        .workflows
        .iter()
        .map(|wf| {
            let fn_name = to_snake_case(&wf.name);
            let call_args = if wf.arguments.is_empty() {
                String::new()
            } else {
                wf.arguments
                    .iter()
                    .map(|a| format!("{name}=cli_args.get(\"{name}\", \"\")", name = a.name))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            format!(
                "        elif workflow_name == \"{name}\":\n            result = asyncio.run({fn_name}({call_args}))",
                name = wf.name,
                fn_name = fn_name,
                call_args = call_args,
            )
        })
        .collect();

    let first_case = cases.first().map(|c| c.replacen("elif", "if", 1)).unwrap_or_default();
    let rest_cases = if cases.len() > 1 { cases[1..].join("\n") } else { String::new() };
    let else_clause = if document.workflows.is_empty() {
        "        print(json.dumps({\"error\": \"no workflows declared\", \"code\": \"E-RUN01\"}), file=sys.stderr)\n        sys.exit(1)".to_owned()
    } else {
        "        else:\n            print(json.dumps({\"error\": f'workflow \"{workflow_name}\" not found', \"code\": \"E-RUN01\"}), file=sys.stderr)\n            sys.exit(1)".to_owned()
    };

    format!(
        r#"if __name__ == "__main__":
    workflow_name = sys.argv[1] if len(sys.argv) > 1 else "--list"
    raw_args = sys.argv[2:]

    if not workflow_name or workflow_name == "--list":
        workflows = [
{}
        ]
        print(json.dumps(workflows))
        sys.exit(0)

    def parse_args(raw):
        out = {{}}
        i = 0
        while i < len(raw):
            if raw[i] == "--arg" and i + 1 < len(raw):
                i += 1
                eq = raw[i].index("=") if "=" in raw[i] else -1
                if eq != -1:
                    out[raw[i][:eq]] = raw[i][eq+1:]
            i += 1
        return out

    cli_args = parse_args(raw_args)
    try:
{}
{}
{}
        result_json = result.model_dump() if hasattr(result, "model_dump") else result
        print(json.dumps(result_json, indent=2))
    except Exception as e:
        print(json.dumps({{"error": str(e), "code": "E-RUN99"}}), file=sys.stderr)
        sys.exit(1)
"#,
        workflow_list.join(",\n"),
        first_case,
        rest_cases,
        else_clause,
    )
}

// ─── Shared Helpers ───────────────────────────────────────────────────────────

fn render_python_type(data_type: &DataType) -> String {
    match data_type {
        DataType::String(_) => "str".to_owned(),
        DataType::Int(_) => "int".to_owned(),
        DataType::Float(_) => "float".to_owned(),
        DataType::Boolean(_) => "bool".to_owned(),
        DataType::List(inner, _) => format!("list[{}]", render_python_type(inner)),
        DataType::Custom(name, _) => name.clone(),
    }
}

fn render_field_config(
    data_type: &DataType,
    constraints: &[Constraint],
) -> CompilerResult<Option<String>> {
    if constraints.is_empty() {
        return Ok(None);
    }
    let mut parts = Vec::new();
    for constraint in constraints {
        match constraint.name.as_str() {
            "min" => {
                let val = render_numeric_constraint_value(constraint)?;
                parts.push(match data_type {
                    DataType::String(_) => format!("min_length={val}"),
                    DataType::List(_, _) => format!("min_length={val}"),
                    _ => format!("ge={val}"),
                });
            }
            "max" => {
                let val = render_numeric_constraint_value(constraint)?;
                parts.push(match data_type {
                    DataType::String(_) => format!("max_length={val}"),
                    DataType::List(_, _) => format!("max_length={val}"),
                    _ => format!("le={val}"),
                });
            }
            "regex" => {
                let pat = render_regex_constraint_value(constraint)?;
                parts.push(format!("pattern={pat}"));
            }
            other => {
                return Err(CompilerError::UnsupportedConstraint {
                    name: other.to_owned(),
                    span: constraint.span.clone(),
                })
            }
        }
    }
    Ok(Some(parts.join(", ")))
}

fn render_numeric_constraint_value(constraint: &Constraint) -> CompilerResult<String> {
    match &constraint.value.expr {
        Expr::IntLiteral(value) => Ok(value.to_string()),
        Expr::FloatLiteral(value) => Ok(trim_float(*value)),
        _ => Err(CompilerError::InvalidConstraintValue {
            name: constraint.name.clone(),
            expected: "a numeric literal".to_owned(),
            span: constraint.span.clone(),
        }),
    }
}

fn render_regex_constraint_value(constraint: &Constraint) -> CompilerResult<String> {
    match &constraint.value.expr {
        Expr::StringLiteral(pattern) => Ok(format!("r\"{}\"", pattern.replace('"', "\\\""))),
        _ => Err(CompilerError::InvalidConstraintValue {
            name: constraint.name.clone(),
            expected: "a string literal".to_owned(),
            span: constraint.span.clone(),
        }),
    }
}

fn trim_float(value: f64) -> String {
    let mut rendered = value.to_string();
    if rendered.ends_with(".0") {
        rendered.truncate(rendered.len() - 2);
    }
    rendered
}

pub fn to_snake_case(name: &str) -> String {
    let mut output = String::with_capacity(name.len() + 4);
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_uppercase() {
            if index > 0 {
                output.push('_');
            }
            output.push(character.to_ascii_lowercase());
        } else {
            output.push(character);
        }
    }
    output
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::generate;
    use crate::ast::{
        Block, ClientDecl, Constraint, DataType, Document, Expr, Span, SpannedExpr, Statement,
        ToolDecl, TypeDecl, TypeField, WorkflowDecl,
    };

    fn spanned(expr: Expr, span: Span) -> SpannedExpr {
        SpannedExpr { expr, span }
    }

    #[test]
    fn emits_baml_style_self_contained_python() {
        let output = generate(&valid_document()).unwrap();

        // Must NOT reference claw_sdk
        assert!(!output.contains("claw_sdk"), "must not import claw_sdk");
        assert!(!output.contains("ClawClient"), "must not reference ClawClient");

        // Must have proper Python imports
        assert!(output.contains("import httpx"));
        assert!(output.contains("from pydantic import BaseModel"));

        // Must have typed Pydantic model
        assert!(output.contains("class SearchResult(BaseModel):"));
        assert!(output.contains("url: str"));

        // Must have agent runner
        assert!(output.contains("async def _run_agent_researcher(task: str)"));

        // Must have typed workflow function
        assert!(output.contains("async def analyze_competitors("));
        assert!(output.contains("-> SearchResult:"));

        // CLI entry
        assert!(output.contains("if __name__ == \"__main__\":"));
        assert!(output.contains("--list"));
    }

    #[test]
    fn lowers_python_field_constraints_into_pydantic_fields() {
        let output = generate(&valid_document()).unwrap();
        assert!(output.contains(r#"Field(pattern=r"^https://")"#));
        assert!(output.contains("Field(ge=0)"));
    }

    #[test]
    fn emits_artifact_saving_when_artifact_spec_present() {
        use crate::ast::ArtifactSpec;
        let mut doc = valid_document();
        doc.workflows[0].artifact = Some(ArtifactSpec {
            format: "markdown".to_owned(),
            path: "~/Desktop/${topic}.md".to_owned(),
            span: 0..0,
        });
        // Rename arg to 'topic' to match artifact path
        doc.workflows[0].arguments[0].name = "topic".to_owned();
        let output = generate(&doc).unwrap();

        assert!(output.contains("_artifact_path"), "must have artifact saving code");
        assert!(output.contains("expanduser"), "must expand ~ in path");
        assert!(output.contains(".write_text("), "must write artifact content");
    }

    fn valid_document() -> Document {
        Document {
            imports: Vec::new(),
            types: vec![TypeDecl {
                name: "SearchResult".to_owned(),
                fields: vec![
                    TypeField {
                        name: "url".to_owned(),
                        data_type: DataType::String(10..16),
                        constraints: vec![Constraint {
                            name: "regex".to_owned(),
                            value: spanned(Expr::StringLiteral("^https://".to_owned()), 17..37),
                            span: 17..37,
                        }],
                        span: 10..37,
                    },
                    TypeField {
                        name: "confidence_score".to_owned(),
                        data_type: DataType::Float(38..43),
                        constraints: vec![Constraint {
                            name: "min".to_owned(),
                            value: spanned(Expr::IntLiteral(0), 44..51),
                            span: 44..51,
                        }],
                        span: 38..51,
                    },
                ],
                span: 0..51,
            }],
            clients: vec![ClientDecl {
                name: "FastAPI".to_owned(),
                provider: "anthropic".to_owned(),
                model: "claude-sonnet-4-6".to_owned(),
                retries: None,
                timeout_ms: None,
                endpoint: None,
                api_key: None,
                span: 52..80,
            }],
            tools: vec![ToolDecl {
                name: "WebSearch".to_owned(),
                arguments: vec![TypeField {
                    name: "query".to_owned(),
                    data_type: DataType::String(81..87),
                    constraints: Vec::new(),
                    span: 81..95,
                }],
                return_type: Some(DataType::Custom("SearchResult".to_owned(), 96..108)),
                invoke_path: Some("module(\"scripts/search\").function(\"run\")".to_owned()),
                using: None,
                synthesizer: None,
                test_block: None,
                secrets: vec![],
                span: 81..130,
            }],
            agents: vec![crate::ast::AgentDecl {
                name: "Researcher".to_owned(),
                extends: None,
                client: Some("FastAPI".to_owned()),
                system_prompt: Some("You are a researcher.".to_owned()),
                tools: vec!["WebSearch".to_owned()],
                dynamic_reasoning: std::cell::Cell::new(false),
                settings: crate::ast::AgentSettings {
                    entries: vec![
                        crate::ast::AgentSetting {
                            name: "max_steps".to_owned(),
                            value: crate::ast::SettingValue::Int(5),
                            span: 131..143,
                        },
                        crate::ast::AgentSetting {
                            name: "temperature".to_owned(),
                            value: crate::ast::SettingValue::Float(0.1),
                            span: 144..160,
                        },
                    ],
                    span: 131..160,
                },
                span: 131..180,
            }],
            workflows: vec![WorkflowDecl {
                name: "AnalyzeCompetitors".to_owned(),
                arguments: vec![TypeField {
                    name: "company".to_owned(),
                    data_type: DataType::String(181..187),
                    constraints: Vec::new(),
                    span: 181..195,
                }],
                return_type: Some(DataType::Custom("SearchResult".to_owned(), 196..208)),
                artifact: None,
                body: Block {
                    statements: vec![
                        Statement::LetDecl {
                            name: "report".to_owned(),
                            explicit_type: Some(DataType::Custom(
                                "SearchResult".to_owned(),
                                209..221,
                            )),
                            value: spanned(
                                Expr::ExecuteRun {
                                    agent_name: "Researcher".to_owned(),
                                    kwargs: vec![(
                                        "task".to_owned(),
                                        spanned(
                                            Expr::Identifier("company".to_owned()),
                                            222..229,
                                        ),
                                    )],
                                    require_type: Some(DataType::Custom(
                                        "SearchResult".to_owned(),
                                        230..242,
                                    )),
                                },
                                209..250,
                            ),
                            span: 209..250,
                        },
                        Statement::Return {
                            value: spanned(Expr::Identifier("report".to_owned()), 251..264),
                            span: 251..264,
                        },
                    ],
                    span: 209..264,
                },
                span: 181..264,
            }],
            listeners: Vec::new(),
            tests: Vec::new(),
            mocks: Vec::new(),
            synthesizers: Vec::new(),
            span: 0..264,
        }
    }
}
