// src/codegen/runtime.rs
// Generates generated/runtime.js — a self-contained headless workflow runner.
// Uses zero npm dependencies (raw fetch for all LLM providers).
// See specs/38-Closed-Loop-Runtime.md and specs/39-Runtime-First-Architecture.md

use std::fs;
use std::path::Path;

use crate::ast::*;
use crate::errors::{CompilerError, CompilerResult};

use super::shared_js;

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    let out_dir = project_root.join("generated");
    fs::create_dir_all(&out_dir)
        .map_err(|e| CompilerError::IoError { message: format!("failed to create generated/: {e}"), span: 0..0 })?;

    let js = emit_runtime(document);

    fs::write(out_dir.join("runtime.js"), js)
        .map_err(|e| CompilerError::IoError { message: format!("failed to write runtime.js: {e}"), span: 0..0 })?;

    Ok(())
}

fn emit_runtime(document: &Document) -> String {
    let mut out = String::new();
    out.push_str(RUNTIME_HEADER);
    out.push_str(&emit_schemas(document));
    out.push_str(&emit_tool_descriptors(document));
    out.push_str(&emit_tool_handlers(document));
    out.push_str(&emit_agent_runners(document));
    out.push_str(&emit_agents(document));
    out.push_str(&emit_plans(document));
    out.push_str(WORKFLOW_EXECUTOR);
    out.push_str(CLI_ENTRY);
    out
}

const RUNTIME_HEADER: &str = r#"// generated/runtime.js
// AUTO-GENERATED by claw build — DO NOT EDIT
// Requires Node.js >= 18 (built-in fetch). No npm install needed.
"use strict";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs/promises";

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

"#;

// ─── Schemas ─────────────────────────────────────────────────────────────────

fn emit_schemas(document: &Document) -> String {
    let mut entries: Vec<String> = Vec::new();
    for t in &document.types {
        let mut props: Vec<String> = Vec::new();
        let mut required: Vec<String> = Vec::new();
        for field in &t.fields {
            props.push(format!("      {}: {}", field.name, json_schema_for(&field.data_type)));
            required.push(format!("\"{}\"", field.name));
        }
        entries.push(format!(
            "  {name}: {{\n    type: \"object\",\n    properties: {{\n{props}\n    }},\n    required: [{req}]\n  }}",
            name = t.name,
            props = props.join(",\n"),
            req = required.join(", "),
        ));
    }
    format!("const SCHEMAS = {{\n{}\n}};\n\n", entries.join(",\n"))
}

fn json_schema_for(dt: &DataType) -> String {
    match dt {
        DataType::String(_)  => "{ type: \"string\" }".to_owned(),
        DataType::Int(_)     => "{ type: \"integer\" }".to_owned(),
        DataType::Float(_)   => "{ type: \"number\" }".to_owned(),
        DataType::Boolean(_) => "{ type: \"boolean\" }".to_owned(),
        DataType::List(inner, _) => {
            format!("{{ type: \"array\", items: {} }}", json_schema_for(inner))
        }
        DataType::Custom(name, _) => {
            format!("SCHEMAS.{}", name)
        }
    }
}

// ─── Tool Descriptors (for agent tool-call loops) ─────────────────────────────

fn emit_tool_descriptors(document: &Document) -> String {
    let mut entries: Vec<String> = Vec::new();
    for tool in &document.tools {
        let props: Vec<String> = tool.arguments.iter()
            .map(|a| format!("      {}: {}", a.name, json_schema_for(&a.data_type)))
            .collect();
        let required: Vec<String> = tool.arguments.iter()
            .map(|a| format!("\"{}\"", a.name))
            .collect();
        entries.push(format!(
            r#"  {{
    name: "{name}",
    description: "Tool {name}",
    inputSchema: {{
      type: "object",
      properties: {{
{props}
      }},
      required: [{req}]
    }}
  }}"#,
            name = tool.name,
            props = props.join(",\n"),
            req = required.join(", "),
        ));
    }
    format!("const TOOLS = [\n{}\n];\n\n", entries.join(",\n"))
}

// ─── Tool Handlers ────────────────────────────────────────────────────────────

fn emit_tool_handlers(document: &Document) -> String {
    let mut handlers: Vec<String> = Vec::new();
    let mut cases: Vec<String> = Vec::new();

    for tool in &document.tools {
        let invoke = tool.invoke_path.as_deref().unwrap_or("");
        let args: Vec<&str> = tool.arguments.iter().map(|a| a.name.as_str()).collect();

        let handler = if invoke.starts_with("module(") {
            let parts: Vec<&str> = invoke.splitn(2, ").function(").collect();
            let module_path = if parts[0].len() > 8 {
                let s = &parts[0][8..];
                &s[..s.rfind('"').unwrap_or(s.len())]
            } else { "scripts/stub" };
            let fn_name = if parts.len() > 1 && parts[1].len() > 1 {
                let s = &parts[1][1..];
                &s[..s.rfind('"').unwrap_or(s.len())]
            } else { "run" };
            format!(
                r#"async function callTool_{name}(args) {{
  const {{ {destructure} }} = args;
  const modPath = path.resolve(__dirname, "../{module}.js");
  const real = await fs.realpath(modPath);
  const rel = path.relative(path.resolve(__dirname, ".."), real);
  if (rel.startsWith("..") || path.isAbsolute(rel)) {{
    throw new Error("tool module resolves outside workspace: {module}");
  }}
  const mod = await import(new URL(real, "file://").href);
  return await mod.{fn}({args_list});
}}"#,
                name = tool.name,
                destructure = args.join(", "),
                module = module_path,
                fn = fn_name,
                args_list = args.join(", "),
            )
        } else {
            // Stub/unknown
            format!(
                r#"async function callTool_{name}(_args) {{
  throw new Error("tool {name}: no handler configured");
}}"#,
                name = tool.name,
            )
        };

        handlers.push(handler);
        cases.push(format!("    case \"{}\": return callTool_{}(input);", tool.name, tool.name));
    }

    let dispatch = format!(
        r#"async function callTool(name, input) {{
  switch (name) {{
{}
    default: throw {{ code: "E-RUN99", message: `unknown tool: ${{name}}` }};
  }}
}}

"#,
        cases.join("\n")
    );

    format!("{}\n{}", handlers.join("\n\n"), dispatch)
}

// ─── Agent Runners ────────────────────────────────────────────────────────────

fn emit_agent_runners(document: &Document) -> String {
    let mut out = String::new();
    for agent in &document.agents {
        let (provider, model) = resolve_client(agent, document);
        let is_local = provider == "local" || provider == "ollama";
        let model_str = model.trim_start_matches("local.").to_owned();

        let system_prompt = agent.system_prompt.as_deref().unwrap_or("")
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n");

        let max_steps: i64 = agent.settings.entries.iter()
            .find(|e| e.name == "max_steps")
            .and_then(|e| if let SettingValue::Int(n) = e.value { Some(n) } else { None })
            .unwrap_or(10);

        let temperature: f64 = agent.settings.entries.iter()
            .find(|e| e.name == "temperature")
            .and_then(|e| match e.value {
                SettingValue::Float(f) => Some(f),
                SettingValue::Int(n)   => Some(n as f64),
                _ => None,
            })
            .unwrap_or(1.0);

        let tools_filter = if agent.tools.is_empty() {
            "TOOLS".to_owned()
        } else {
            let names: Vec<String> = agent.tools.iter()
                .map(|t| format!("\"{}\"", t))
                .collect();
            format!("TOOLS.filter(t => [{}].includes(t.name))", names.join(", "))
        };

        let fn_name = format!("runAgent_{}", agent.name);
        let body = if is_local {
            shared_js::emit_agent_runner_ollama_fetch(
                &fn_name, &system_prompt, &model_str, max_steps, temperature, &tools_filter,
            )
        } else {
            shared_js::emit_agent_runner_anthropic_fetch(
                &fn_name, &system_prompt, &model_str, max_steps, temperature, &tools_filter,
            )
        };

        out.push_str(&body);
        out.push_str("\n\n");
    }

    // Generic dispatcher
    let mut dispatch_cases: Vec<String> = document.agents.iter()
        .map(|a| format!("    case \"{}\": return runAgent_{}(task);", a.name, a.name))
        .collect();

    if dispatch_cases.is_empty() {
        dispatch_cases.push("    // no agents declared".to_owned());
    }

    out.push_str(&format!(
        r#"async function runAgent(agentName, task) {{
  switch (agentName) {{
{}
    default:
      throw {{ code: "E-RUN01", message: `agent "${{agentName}}" not found` }};
  }}
}}

"#,
        dispatch_cases.join("\n")
    ));

    out
}

fn resolve_client(agent: &AgentDecl, document: &Document) -> (String, String) {
    if let Some(client_name) = &agent.client {
        if let Some(c) = document.clients.iter().find(|c| &c.name == client_name) {
            return (c.provider.clone(), c.model.clone());
        }
    }
    if let Some(c) = document.clients.first() {
        return (c.provider.clone(), c.model.clone());
    }
    ("anthropic".to_owned(), "claude-haiku-4-5-20251001".to_owned())
}

// ─── AGENTS config object ─────────────────────────────────────────────────────

fn emit_agents(document: &Document) -> String {
    let mut entries: Vec<String> = Vec::new();
    for agent in &document.agents {
        let (provider, model) = resolve_client(agent, document);
        let model_str = model.trim_start_matches("local.").to_owned();
        entries.push(format!(
            r#"  {name}: {{ provider: "{provider}", model: "{model}", runner: runAgent_{name} }}"#,
            name    = agent.name,
            provider = provider,
            model   = model_str,
        ));
    }
    format!("const AGENTS = {{\n{}\n}};\n\n", entries.join(",\n"))
}

// ─── Plans ────────────────────────────────────────────────────────────────────

fn emit_plans(document: &Document) -> String {
    let mut entries: Vec<String> = Vec::new();
    for wf in &document.workflows {
        let req_args: Vec<String> = wf.arguments.iter()
            .map(|a| format!("\"{}\"", a.name))
            .collect();

        let return_type = match &wf.return_type {
            Some(DataType::Custom(name, _)) => format!("\"{}\"", name),
            Some(_) => "\"any\"".to_owned(),
            None => "null".to_owned(),
        };

        let steps = compile_steps(&wf.body);

        entries.push(format!(
            r#"  {name}: {{
    name: "{name}",
    requiredArgs: [{req}],
    returnType: {ret},
    steps: {steps}
  }}"#,
            name  = wf.name,
            req   = req_args.join(", "),
            ret   = return_type,
            steps = steps,
        ));
    }
    format!("const PLANS = {{\n{}\n}};\n\n", entries.join(",\n"))
}

fn compile_steps(block: &Block) -> String {
    let mut steps: Vec<String> = Vec::new();
    for stmt in &block.statements {
        compile_statement(stmt, &mut steps);
    }
    format!("[\n{}\n    ]", steps.join(",\n"))
}

fn compile_statement(stmt: &Statement, steps: &mut Vec<String>) {
    match stmt {
        Statement::LetDecl { name, value, .. } => {
            if let Expr::ExecuteRun { agent_name, kwargs, require_type } = &value.expr {
                let task_template = extract_task_template(kwargs);
                let req_type = require_type.as_ref()
                    .and_then(|dt| if let DataType::Custom(n, _) = dt { Some(n.as_str()) } else { None })
                    .map(|s| format!("\"{}\"", s))
                    .unwrap_or_else(|| "null".to_owned());
                steps.push(format!(
                    r#"      {{ type: "execute_agent", bind: "{bind}", agent: "{agent}", taskTemplate: {tmpl}, requireType: {req} }}"#,
                    bind  = name,
                    agent = agent_name,
                    tmpl  = task_template,
                    req   = req_type,
                ));
            } else {
                // Non-agent let binding — store as literal
                let val = expr_to_js_literal(&value.expr);
                steps.push(format!(
                    r#"      {{ type: "let", bind: "{}", value: {} }}"#,
                    name, val
                ));
            }
        }

        Statement::ExecuteRun { agent_name, kwargs, require_type, .. } => {
            let task_template = extract_task_template(kwargs);
            let req_type = require_type.as_ref()
                .and_then(|dt| if let DataType::Custom(n, _) = dt { Some(n.as_str()) } else { None })
                .map(|s| format!("\"{}\"", s))
                .unwrap_or_else(|| "null".to_owned());
            steps.push(format!(
                r#"      {{ type: "execute_agent", bind: "_", agent: "{agent}", taskTemplate: {tmpl}, requireType: {req} }}"#,
                agent = agent_name,
                tmpl  = task_template,
                req   = req_type,
            ));
        }

        Statement::Return { value, .. } => {
            let val_js = match &value.expr {
                Expr::Identifier(name) => format!("{{ type: \"var\", name: \"{}\" }}", name),
                other => format!("{{ type: \"literal\", value: {} }}", expr_to_js_literal(other)),
            };
            steps.push(format!("      {{ type: \"return\", value: {} }}", val_js));
        }

        Statement::Reason { using_agent, goal, bind, .. } => {
            // Compile to execute_agent step
            steps.push(format!(
                r#"      {{ type: "execute_agent", bind: "{bind}", agent: "{agent}", taskTemplate: "{goal}", requireType: null }}"#,
                bind  = bind,
                agent = using_agent,
                goal  = goal.replace('"', "\\\""),
            ));
        }

        Statement::ForLoop { item_name, .. } => {
            // v1: describe the loop as a task — W-RUN01 emitted at build time
            eprintln!("warning[W-RUN01]: `for {}` loop compiled to simplified execute_agent step in v1", item_name);
            steps.push(format!(
                r#"      {{ type: "execute_agent", bind: "_", agent: "_loop", taskTemplate: "Process the for loop over {}", requireType: null }}"#,
                item_name
            ));
        }

        Statement::IfCond { .. } => {
            eprintln!("warning[W-RUN01]: `if` condition compiled to simplified execute_agent step in v1");
            steps.push(
                r#"      { type: "execute_agent", bind: "_", agent: "_cond", taskTemplate: "Evaluate the conditional branch", requireType: null }"#.to_owned()
            );
        }

        Statement::Assert { .. }
        | Statement::Continue(_)
        | Statement::Break(_)
        | Statement::TryCatch { .. }
        | Statement::Expression(_) => {
            // Skip non-workflow-affecting statements
        }
    }
}

fn extract_task_template(kwargs: &[(String, SpannedExpr)]) -> String {
    for (key, val) in kwargs {
        if key == "task" {
            if let Expr::StringLiteral(s) = &val.expr {
                // Use a regular JS string — interpolate() will expand ${var} at runtime
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"");
                return format!("\"{}\"", escaped);
            }
        }
    }
    "\"<no task>\"".to_owned()
}

fn expr_to_js_literal(expr: &Expr) -> String {
    match expr {
        Expr::StringLiteral(s)  => format!("\"{}\"", s.replace('"', "\\\"")),
        Expr::IntLiteral(n)     => n.to_string(),
        Expr::FloatLiteral(f)   => f.to_string(),
        Expr::BoolLiteral(b)    => b.to_string(),
        Expr::Identifier(name)  => format!("scope[\"{}\"]", name),
        _                        => "null".to_owned(),
    }
}

// ─── Workflow Executor (static) ───────────────────────────────────────────────

const WORKFLOW_EXECUTOR: &str = r#"
// ── Schema Validation ─────────────────────────────────────────────────────────

function validateAgainstSchema(value, schema, typeName) {
  if (!schema || schema.type !== "object") return;
  for (const req of (schema.required ?? [])) {
    if (!(req in value)) {
      throw {
        code: "E-RUN03",
        message: `type validation failed — return type "${typeName}" not satisfied: missing field "${req}"\n  got: ${JSON.stringify(value)}`,
      };
    }
  }
}

function parseAndValidate(output, typeName) {
  let parsed;
  try {
    parsed = typeof output === "string" ? JSON.parse(output) : output;
  } catch {
    // LLM returned plain text — wrap it
    parsed = { text: output };
  }
  const schema = SCHEMAS[typeName];
  if (schema) validateAgainstSchema(parsed, schema, typeName);
  return parsed;
}

function interpolate(template, scope) {
  return template.replace(/\$\{(\w+)\}/g, (_, k) => scope[k] ?? "");
}

function resolveValue(valueSpec, scope) {
  if (valueSpec.type === "var")     return scope[valueSpec.name];
  if (valueSpec.type === "literal") return valueSpec.value;
  return null;
}

// ── Workflow Executor ─────────────────────────────────────────────────────────

async function executeWorkflow(planName, args) {
  const plan = PLANS[planName];
  if (!plan) {
    const available = Object.keys(PLANS).join(", ") || "(none)";
    throw {
      code: "E-RUN01",
      message: `workflow "${planName}" not found\n  available: ${available}\n  hint: run \`claw build\` to recompile`,
    };
  }

  for (const required of plan.requiredArgs) {
    if (!(required in args)) {
      throw {
        code: "E-RUN02",
        message: `missing required argument "${required}" for workflow "${planName}"\n  usage: claw run ${planName} --arg ${required}=<value>`,
      };
    }
  }

  const scope = { ...args };

  for (const step of plan.steps) {
    if (step.type === "execute_agent") {
      const task = interpolate(step.taskTemplate, scope);
      const output = await runAgent(step.agent, task);
      scope[step.bind] = step.requireType
        ? parseAndValidate(output, step.requireType)
        : output;
    } else if (step.type === "let") {
      scope[step.bind] = step.value;
    } else if (step.type === "return") {
      return resolveValue(step.value, scope);
    }
  }

  return null;
}

"#;

// ─── CLI Entry (static) ───────────────────────────────────────────────────────

const CLI_ENTRY: &str = r#"
// ── CLI Entry ─────────────────────────────────────────────────────────────────

if (typeof fetch === "undefined") {
  process.stderr.write(JSON.stringify({
    error: "Node.js >= 18 required — built-in fetch() not available",
    code: "E-RT01"
  }) + "\n");
  process.exit(1);
}

function parseCliArgs(rawArgs) {
  const result = {};
  for (let i = 0; i < rawArgs.length; i++) {
    if (rawArgs[i] === "--arg" && i + 1 < rawArgs.length) {
      const eq = rawArgs[++i].indexOf("=");
      if (eq !== -1) result[rawArgs[i].slice(0, eq)] = rawArgs[i].slice(eq + 1);
    }
  }
  return result;
}

function exitCodeFor(code) {
  const MAP = { "E-RUN01": 1, "E-RUN02": 2, "E-RUN03": 3, "E-RUN04": 4, "E-RUN05": 5, "E-RT01": 1, "E-RT03": 4 };
  return MAP[code] ?? 1;
}

const [,, workflowName, ...rawArgs] = process.argv;

if (!workflowName || workflowName === "--list") {
  const plans = Object.values(PLANS).map(p => ({
    name: p.name, requiredArgs: p.requiredArgs, returnType: p.returnType ?? null,
  }));
  process.stdout.write(JSON.stringify(plans) + "\n");
  process.exit(0);
}

const cliArgs = parseCliArgs(rawArgs);

(async () => {
  try {
    const result = await executeWorkflow(workflowName, cliArgs);
    process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    process.exit(0);
  } catch (err) {
    process.stderr.write(JSON.stringify({ error: err.message ?? String(err), code: err.code ?? "E-RUN99" }) + "\n");
    process.exit(exitCodeFor(err.code));
  }
})();
"#;
