use std::fs;
use std::path::Path;

use crate::ast::{ClientDecl, Document, SynthesizerDecl};
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    // Only generate if there are synthesis-path tools or synthesizer declarations
    let has_synthesis_tools = document.tools.iter().any(|t| t.using.is_some());
    if !has_synthesis_tools && document.synthesizers.is_empty() {
        return Ok(());
    }

    let gen_dir = project_root.join("generated");
    fs::create_dir_all(&gen_dir).map_err(|e| CompilerError::IoError {
        message: format!("failed to create generated directory: {e}"),
        span: 0..0,
    })?;

    let synth = resolve_synthesizer(document);
    let script = build_synth_runner(synth, document);

    fs::write(gen_dir.join("synth-runner.js"), script).map_err(|e| CompilerError::IoError {
        message: format!("failed to write synth-runner.js: {e}"),
        span: 0..0,
    })?;

    Ok(())
}

struct SynthConfig {
    provider: String,
    model: String,
    temperature: f64,
    max_tokens: u64,
}

fn resolve_synthesizer(document: &Document) -> SynthConfig {
    // Pick the first synthesizer declaration if present, else fall back to first client
    if let Some(synth) = document.synthesizers.first() {
        // Look up the client the synthesizer references
        if let Some(client) = document.clients.iter().find(|c| c.name == synth.client) {
            return SynthConfig {
                provider: client.provider.clone(),
                model: client.model.clone(),
                temperature: synth.temperature.unwrap_or(0.1),
                max_tokens: synth.max_tokens.unwrap_or(8192),
            };
        }
    }

    // Fall back to first client in document
    if let Some(client) = document.clients.first() {
        return SynthConfig {
            provider: client.provider.clone(),
            model: client.model.clone(),
            temperature: 0.1,
            max_tokens: 8192,
        };
    }

    // Ultimate default
    SynthConfig {
        provider: "anthropic".to_owned(),
        model: "claude-sonnet-4-6".to_owned(),
        temperature: 0.1,
        max_tokens: 8192,
    }
}

fn build_synth_runner(config: SynthConfig, document: &Document) -> String {
    let adapter_import = adapter_import(&config.provider);
    let adapter_class = adapter_class(&config.provider);
    let api_key_env = api_key_env(&config.provider, &config.model);

    // Determine if this is a local (ollama) model
    let is_local = config.model.starts_with("local.") || config.provider == "ollama";
    let model_id = if is_local {
        config.model.trim_start_matches("local.").to_owned()
    } else {
        config.model.clone()
    };

    let adapter_args = if is_local {
        format!(
            r#"{{
  model: '{model_id}',
  temperature: {temp},
  maxTokens: {max_tokens},
  baseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434/v1',
}}"#,
            temp = config.temperature,
            max_tokens = config.max_tokens,
        )
    } else {
        format!(
            r#"{{
  model: '{model_id}',
  temperature: {temp},
  maxTokens: {max_tokens},
  apiKey: {api_key_env},
}}"#,
            temp = config.temperature,
            max_tokens = config.max_tokens,
        )
    };

    format!(
        r#"// generated/synth-runner.js — auto-generated by claw compile. Do not edit.
// This script is the Synthesis Pass bridge: reads SynthesisRequest from stdin,
// writes SynthesisResponse to stdout (one JSON object per line, NDJSON).

import {{ createInterface }} from 'node:readline';
{adapter_import}

const adapter = new {adapter_class}({adapter_args});

const rl = createInterface({{ input: process.stdin, terminal: false }});
const pending = [];

rl.on('line', (line) => {{
  let request;
  try {{
    request = JSON.parse(line);
  }} catch (e) {{
    process.stdout.write(JSON.stringify({{ error: 'invalid JSON: ' + e.message }}) + '\n');
    return;
  }}

  const p = adapter.synthesize(request)
    .then((response) => {{
      process.stdout.write(JSON.stringify(response) + '\n');
    }})
    .catch((err) => {{
      process.stderr.write('[synth-runner] error: ' + err.message + '\n');
      process.stdout.write(JSON.stringify({{ error: err.message }}) + '\n');
    }});

  pending.push(p);
}});

rl.on('close', async () => {{
  await Promise.all(pending);
}});
"#,
    )
}

fn adapter_import(provider: &str) -> &'static str {
    match provider {
        "anthropic" => "import { AnthropicAdapter } from '@claw/synth-adapters/anthropic.js';",
        "openai" => "import { OpenAIAdapter } from '@claw/synth-adapters/openai.js';",
        "ollama" => "import { OllamaAdapter } from '@claw/synth-adapters/ollama.js';",
        "openrouter" => "import { OpenRouterAdapter } from '@claw/synth-adapters/openrouter.js';",
        _ => "import { AnthropicAdapter } from '@claw/synth-adapters/anthropic.js';",
    }
}

fn adapter_class(provider: &str) -> &'static str {
    match provider {
        "anthropic" => "AnthropicAdapter",
        "openai" => "OpenAIAdapter",
        "ollama" => "OllamaAdapter",
        "openrouter" => "OpenRouterAdapter",
        _ => "AnthropicAdapter",
    }
}

fn api_key_env(provider: &str, _model: &str) -> &'static str {
    match provider {
        "anthropic" => "process.env.ANTHROPIC_API_KEY",
        "openai" => "process.env.OPENAI_API_KEY",
        "openrouter" => "process.env.OPENROUTER_API_KEY",
        _ => "undefined",
    }
}
