// src/codegen/ts_reason.rs
// Generates generated/runtime/reason.ts — the runtime reasoning layer.
//
// This module is imported by synthesized workflow TypeScript for `reason {}` blocks.
// It provides:
//   - reason<T>()         — calls the agent's LLM at execution time, validates output
//   - judgeReason()       — asks the agent to evaluate output against a goal (bool)
//   - clawReSynthesize()  — spawns `claw synthesize` to regenerate tool implementations
//
// Fixes spec 32 §5 / C-01 from spec 47: workflows must not import from non-existent
// `../agents/*.js` files; they import the `reason()` function from this module instead.

use std::fs;
use std::path::Path;

use crate::ast::{AgentDecl, Document};
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    // Only generate if there are agents (reason{} blocks need them)
    if document.agents.is_empty() {
        return Ok(());
    }

    let runtime_dir = project_root.join("generated").join("runtime");
    fs::create_dir_all(&runtime_dir).map_err(|e| CompilerError::IoError {
        message: format!("failed to create generated/runtime/: {e}"),
        span: 0..0,
    })?;

    let content = emit_reason_module(document);
    fs::write(runtime_dir.join("reason.ts"), content).map_err(|e| CompilerError::IoError {
        message: format!("failed to write runtime/reason.ts: {e}"),
        span: 0..0,
    })?;

    Ok(())
}

fn emit_reason_module(document: &Document) -> String {
    let mut out = String::new();

    out.push_str("// generated/runtime/reason.ts\n");
    out.push_str("// AUTO-GENERATED by claw build — do not edit.\n");
    out.push_str("// Runtime implementation for reason{} blocks in synthesized workflows.\n\n");

    out.push_str("import { execFile } from 'node:child_process';\n");
    out.push_str("import { promisify } from 'node:util';\n\n");

    out.push_str("const _execFile = promisify(execFile);\n\n");

    // Bake agent configs into the module
    out.push_str("// Agent configurations resolved at compile time from .claw source.\n");
    out.push_str("const AGENT_CONFIGS: Record<string, {\n");
    out.push_str("  provider: string;\n");
    out.push_str("  model: string;\n");
    out.push_str("  systemPrompt: string;\n");
    out.push_str("  apiKeyEnv: string;\n");
    out.push_str("}> = {\n");

    for agent in &document.agents {
        let (provider, model, api_key_env) = resolve_agent_client(agent, document);
        let system_prompt = agent.system_prompt.as_deref().unwrap_or("")
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n");
        out.push_str(&format!(
            "  \"{name}\": {{ provider: \"{provider}\", model: \"{model}\", systemPrompt: \"{sp}\", apiKeyEnv: \"{key}\" }},\n",
            name = agent.name,
            provider = provider,
            model = model,
            sp = system_prompt,
            key = api_key_env,
        ));
    }

    out.push_str("};\n\n");

    out.push_str(REASON_RUNTIME_BODY);
    out
}

fn resolve_agent_client(agent: &AgentDecl, document: &Document) -> (String, String, String) {
    let client = agent.client.as_deref()
        .and_then(|name| document.clients.iter().find(|c| c.name == name))
        .or_else(|| document.clients.first());

    if let Some(c) = client {
        let api_key_env = api_key_env_for(&c.provider);
        let model = c.model.trim_start_matches("local.").to_owned();
        (c.provider.clone(), model, api_key_env)
    } else {
        ("anthropic".to_owned(), "claude-haiku-4-5-20251001".to_owned(), "ANTHROPIC_API_KEY".to_owned())
    }
}

fn api_key_env_for(provider: &str) -> String {
    match provider {
        "anthropic" => "ANTHROPIC_API_KEY".to_owned(),
        "openai"    => "OPENAI_API_KEY".to_owned(),
        "local" | "ollama" => String::new(),
        other => format!("{}_API_KEY", other.to_uppercase()),
    }
}

const REASON_RUNTIME_BODY: &str = r#"
// ── Public API ────────────────────────────────────────────────────────────────

/**
 * reason() — call an agent's LLM at execution time with a goal and input.
 * Used by compiled `reason {}` blocks in synthesized workflows.
 *
 * @param opts.agent   - agent name (must be declared in .claw source)
 * @param opts.input   - runtime input value (any type, serialized as JSON context)
 * @param opts.goal    - natural-language goal string from the .claw reason{} block
 * @returns Parsed JSON output validated to type T
 */
export async function reason<T>(opts: {
  agent: string;
  input: unknown;
  goal: string;
}): Promise<T> {
  const config = AGENT_CONFIGS[opts.agent];
  if (!config) {
    throw new Error(`reason: unknown agent "${opts.agent}". Declared agents: ${Object.keys(AGENT_CONFIGS).join(", ")}`);
  }
  const prompt = buildReasonPrompt(opts.input, opts.goal);
  const raw = await callAgentLLM(config, prompt);
  return parseJsonOutput<T>(raw, opts.agent, "reason");
}

/**
 * judgeReason() — ask the agent to evaluate whether output meets the goal.
 * Used by `on_fail: retry(max: N)` compiled loops.
 *
 * @returns true if the agent considers the output acceptable; false otherwise.
 */
export async function judgeReason(opts: {
  agent: string;
  result: unknown;
  goal: string;
}): Promise<boolean> {
  const config = AGENT_CONFIGS[opts.agent];
  if (!config) {
    throw new Error(`judgeReason: unknown agent "${opts.agent}"`);
  }
  const prompt = buildJudgePrompt(opts.result, opts.goal);
  const raw = await callAgentLLM(config, prompt);
  const text = raw.trim().toLowerCase();
  return text.startsWith("yes") || text.startsWith("true") || text.startsWith("accept") || text.startsWith("pass");
}

/**
 * clawReSynthesize() — spawn `claw synthesize` to regenerate tool implementations.
 * Used by `on_fail: re_synthesize` in compiled reason{} blocks.
 */
export async function clawReSynthesize(): Promise<void> {
  try {
    await _execFile("claw", ["synthesize"]);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`clawReSynthesize: claw synthesize failed: ${msg}`);
  }
}

// ── Internal helpers ──────────────────────────────────────────────────────────

function buildReasonPrompt(input: unknown, goal: string): string {
  const ctx = typeof input === "string" ? input : JSON.stringify(input, null, 2);
  return `CONTEXT:\n${ctx}\n\nGOAL: ${goal}\n\nRespond with valid JSON only. No markdown fences, no explanation.`;
}

function buildJudgePrompt(result: unknown, goal: string): string {
  const ctx = typeof result === "string" ? result : JSON.stringify(result, null, 2);
  return `Does the following output satisfy the stated goal?\n\nGOAL: ${goal}\n\nOUTPUT:\n${ctx}\n\nAnswer with YES or NO only.`;
}

function parseJsonOutput<T>(raw: string, agentName: string, caller: string): T {
  // Strip optional markdown code fences the LLM may wrap JSON in
  const fenced = raw.match(/```(?:json)?\s*([\s\S]+?)```/);
  const jsonStr = (fenced ? fenced[1] : raw).trim();
  try {
    return JSON.parse(jsonStr) as T;
  } catch {
    throw new Error(
      `${caller}[${agentName}]: LLM returned non-JSON response.\n` +
      `  First 300 chars: ${jsonStr.slice(0, 300)}`
    );
  }
}

async function callAgentLLM(
  config: { provider: string; model: string; systemPrompt: string; apiKeyEnv: string },
  prompt: string,
): Promise<string> {
  if (config.provider === "local" || config.provider === "ollama") {
    return callOllama(config.model, config.systemPrompt, prompt);
  }
  return callAnthropic(config.model, config.systemPrompt, prompt, config.apiKeyEnv);
}

async function callOllama(model: string, systemPrompt: string, prompt: string): Promise<string> {
  const response = await fetch("http://localhost:11434/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user",   content: prompt },
      ],
      stream: false,
    }),
  });
  if (!response.ok) {
    throw new Error(`Ollama API error ${response.status}: ${await response.text()}`);
  }
  const data = await response.json() as { choices?: Array<{ message?: { content?: string } }> };
  return data.choices?.[0]?.message?.content ?? "";
}

async function callAnthropic(
  model: string,
  systemPrompt: string,
  prompt: string,
  apiKeyEnv: string,
): Promise<string> {
  const apiKey = process.env[apiKeyEnv];
  if (!apiKey) {
    throw new Error(`reason: env var ${apiKeyEnv} is not set. Export it before running this workflow.`);
  }
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model,
      system: systemPrompt,
      messages: [{ role: "user", content: prompt }],
      max_tokens: 4096,
    }),
  });
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`Anthropic API error ${response.status}: ${body}`);
  }
  const data = await response.json() as { content?: Array<{ text?: string }> };
  return data.content?.[0]?.text ?? "";
}
"#;
