use std::fs;
use std::path::Path;

use crate::ast::{Constraint, DataType, Document, Expr, ExpectOp, TestBlock, ToolDecl};
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    let has_synthesis_tools = document.tools.iter().any(|t| t.using.is_some());
    if !has_synthesis_tools {
        return Ok(());
    }

    let tests_dir = project_root.join("generated").join("__tests__");
    fs::create_dir_all(&tests_dir).map_err(|e| CompilerError::IoError {
        message: format!("failed to create __tests__ directory: {e}"),
        span: 0..0,
    })?;

    for tool in &document.tools {
        if tool.using.is_none() {
            continue;
        }

        let content = emit_tool_test(tool, document);
        let filename = format!("{}.test.ts", tool.name);
        fs::write(tests_dir.join(&filename), content).map_err(|e| CompilerError::IoError {
            message: format!("failed to write test {}: {e}", filename),
            span: tool.span.clone(),
        })?;
    }

    Ok(())
}

fn emit_tool_test(tool: &ToolDecl, document: &Document) -> String {
    let mut out = String::from(
        "// auto-generated by claw compile. Do not edit.\n",
    );
    out.push_str("import { describe, it, expect } from 'vitest';\n");
    out.push_str(&format!("import {{ {} }} from '../tools/{}.js';\n\n", tool.name, tool.name));

    // Import types used in test assertions
    let output_type_name = tool.return_type.as_ref().and_then(|dt| match dt {
        DataType::Custom(name, _) => Some(name.clone()),
        _ => None,
    });
    if let Some(ref type_name) = output_type_name {
        if document.types.iter().any(|t| &t.name == type_name) {
            out.push_str(&format!("import {{ {}Schema }} from '../types.js';\n\n", type_name));
        }
    }

    out.push_str(&format!("describe('{}', () => {{\n", tool.name));

    // Tier 1: contract test — always generated from return type shape
    out.push_str("  // Tier 1: contract test (output shape validation)\n");
    out.push_str("  it('contract:output_shape', async () => {\n");

    let placeholder_args = emit_placeholder_args(tool);
    out.push_str(&format!("    const result = await {}({});\n", tool.name, placeholder_args));
    out.push_str("    expect(result).toBeDefined();\n");

    if let Some(rt) = &tool.return_type {
        emit_type_assertions(&mut out, rt, "result", document);
    }
    out.push_str("  });\n");

    // Tier 2: behavior tests from test{} block
    if let Some(tb) = &tool.test_block {
        out.push('\n');
        out.push_str("  // Tier 2: behavior tests (declared in .claw test{} block)\n");
        emit_behavior_test(&mut out, tool, tb);
    }

    out.push_str("});\n");
    out
}

fn emit_placeholder_args(tool: &ToolDecl) -> String {
    if tool.arguments.is_empty() {
        return "{}".to_owned();
    }

    // If there's a test block, use its inputs
    if let Some(tb) = &tool.test_block {
        let args: Vec<String> = tb.input.iter()
            .map(|(key, val)| {
                let val_str = match &val.expr {
                    crate::ast::Expr::StringLiteral(s) => format!("{:?}", s),
                    crate::ast::Expr::IntLiteral(n) => n.to_string(),
                    crate::ast::Expr::FloatLiteral(f) => f.to_string(),
                    crate::ast::Expr::BoolLiteral(b) => b.to_string(),
                    _ => "undefined".to_owned(),
                };
                format!("{}: {}", key, val_str)
            })
            .collect();
        return format!("{{ {} }}", args.join(", "));
    }

    // Generate type-appropriate placeholder values
    let args: Vec<String> = tool.arguments.iter()
        .map(|field| {
            let placeholder = type_placeholder(&field.data_type, &field.name, &field.constraints);
            format!("{}: {}", field.name, placeholder)
        })
        .collect();
    format!("{{ {} }}", args.join(", "))
}

fn constraint_min_value(constraints: &[Constraint]) -> Option<String> {
    constraints.iter()
        .find(|c| c.name == "min")
        .map(|c| match &c.value.expr {
            Expr::IntLiteral(n) => n.to_string(),
            Expr::FloatLiteral(f) => f.to_string(),
            _ => String::new(),
        })
        .filter(|s| !s.is_empty())
}

fn type_placeholder(dt: &DataType, field_name: &str, constraints: &[Constraint]) -> String {
    match dt {
        DataType::String(_) => {
            if field_name.contains("url") || field_name.contains("endpoint") {
                "\"https://example.com\"".to_owned()
            } else if field_name.contains("query") || field_name.contains("search") {
                "\"test query\"".to_owned()
            } else {
                format!("\"test-{}\"", field_name)
            }
        }
        DataType::Int(_) => {
            constraint_min_value(constraints).unwrap_or_else(|| "1".to_owned())
        }
        DataType::Float(_) => {
            constraint_min_value(constraints).unwrap_or_else(|| "1.0".to_owned())
        }
        DataType::Boolean(_) => "true".to_owned(),
        DataType::List(_, _) => "[]".to_owned(),
        DataType::Custom(name, _) => format!("{{}} as {}", name),
    }
}

fn emit_type_assertions(out: &mut String, dt: &DataType, var: &str, document: &Document) {
    match dt {
        DataType::String(_) => {
            out.push_str(&format!("    expect(typeof {var}).toBe('string');\n"));
        }
        DataType::Int(_) | DataType::Float(_) => {
            out.push_str(&format!("    expect(typeof {var}).toBe('number');\n"));
        }
        DataType::Boolean(_) => {
            out.push_str(&format!("    expect(typeof {var}).toBe('boolean');\n"));
        }
        DataType::List(_, _) => {
            out.push_str(&format!("    expect(Array.isArray({var})).toBe(true);\n"));
        }
        DataType::Custom(type_name, _) => {
            // Use Zod schema parse for complex types
            out.push_str(&format!(
                "    expect(() => {type_name}Schema.parse({var})).not.toThrow();\n"
            ));
            // Also emit field-level checks for the type's fields
            if let Some(type_decl) = document.types.iter().find(|t| &t.name == type_name) {
                for field in &type_decl.fields {
                    let field_var = format!("{var}.{}", field.name);
                    out.push_str(&format!("    expect({field_var}).toBeDefined();\n"));
                }
            }
        }
    }
}

fn emit_behavior_test(out: &mut String, tool: &ToolDecl, tb: &TestBlock) {
    let args: Vec<String> = tb.input.iter()
        .map(|(key, val)| {
            let val_str = match &val.expr {
                crate::ast::Expr::StringLiteral(s) => format!("{:?}", s),
                crate::ast::Expr::IntLiteral(n) => n.to_string(),
                crate::ast::Expr::FloatLiteral(f) => f.to_string(),
                crate::ast::Expr::BoolLiteral(b) => b.to_string(),
                _ => "undefined".to_owned(),
            };
            format!("{}: {}", key, val_str)
        })
        .collect();
    let args_str = format!("{{ {} }}", args.join(", "));

    out.push_str("  it('behavior:declared_test', async () => {\n");
    out.push_str(&format!("    const result = await {}({});\n", tool.name, args_str));

    for (field, op) in &tb.expect {
        let assertion = emit_expect_assertion(field, op);
        out.push_str(&format!("    {};\n", assertion));
    }

    out.push_str("  });\n");
}

fn emit_expect_assertion(field: &str, op: &ExpectOp) -> String {
    let access = format!("result.{field}");
    match op {
        ExpectOp::NotEmpty => {
            format!("expect({access}).toBeTruthy()")
        }
        ExpectOp::Gt(n) => format!("expect({access}).toBeGreaterThan({})", n),
        ExpectOp::Lt(n) => format!("expect({access}).toBeLessThan({})", n),
        ExpectOp::Gte(n) => format!("expect({access}).toBeGreaterThanOrEqual({})", n),
        ExpectOp::Lte(n) => format!("expect({access}).toBeLessThanOrEqual({})", n),
        ExpectOp::Eq(expr) => {
            let val = match &expr.expr {
                crate::ast::Expr::StringLiteral(s) => format!("{:?}", s),
                crate::ast::Expr::IntLiteral(n) => n.to_string(),
                crate::ast::Expr::FloatLiteral(f) => f.to_string(),
                crate::ast::Expr::BoolLiteral(b) => b.to_string(),
                _ => "undefined".to_owned(),
            };
            format!("expect({access}).toBe({})", val)
        }
        ExpectOp::Matches(pattern) => {
            format!("expect({access}).toMatch(/{}/)", pattern)
        }
    }
}
