use std::fs;
use std::path::Path;

use crate::ast::{Constraint, DataType, Document, Expr};
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    let gen_dir = project_root.join("generated");
    fs::create_dir_all(&gen_dir).map_err(|e| CompilerError::IoError {
        message: format!("failed to create generated directory: {e}"),
        span: 0..0,
    })?;

    let content = build_types_ts(document);

    fs::write(gen_dir.join("types.ts"), content).map_err(|e| CompilerError::IoError {
        message: format!("failed to write types.ts: {e}"),
        span: 0..0,
    })?;

    Ok(())
}

fn build_types_ts(document: &Document) -> String {
    let mut out = String::from(
        "// generated/types.ts — auto-generated by claw compile. Do not edit.\n\n",
    );

    for t in &document.types {
        out.push_str(&format!("export interface {} {{\n", t.name));
        for field in &t.fields {
            let ts_type = data_type_to_ts(&field.data_type);
            let constraint_comment = constraint_comment(&field.constraints);
            if !constraint_comment.is_empty() {
                out.push_str(&format!("  /** {} */\n", constraint_comment));
            }
            out.push_str(&format!("  {}: {};\n", field.name, ts_type));
        }
        out.push_str("}\n\n");
    }

    // Also emit Zod schemas for runtime validation used in test tier 1
    out.push_str("// --- Zod schemas (contract test validators) ---\n");
    out.push_str("import { z } from 'zod';\n\n");

    for t in &document.types {
        out.push_str(&format!("export const {}Schema = z.object({{\n", t.name));
        for field in &t.fields {
            let zod_type = data_type_to_zod(&field.data_type, &field.constraints);
            out.push_str(&format!("  {}: {},\n", field.name, zod_type));
        }
        out.push_str("});\n\n");
    }

    out
}

fn data_type_to_ts(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => "string".to_owned(),
        DataType::Int(_) => "number".to_owned(),
        DataType::Float(_) => "number".to_owned(),
        DataType::Boolean(_) => "boolean".to_owned(),
        DataType::List(inner, _) => format!("{}[]", data_type_to_ts(inner)),
        DataType::Custom(name, _) => name.clone(),
    }
}

fn constraint_value_str(c: &Constraint) -> String {
    match &c.value.expr {
        Expr::IntLiteral(n) => n.to_string(),
        Expr::FloatLiteral(f) => f.to_string(),
        Expr::StringLiteral(s) => s.clone(),
        _ => String::new(),
    }
}

fn data_type_to_zod(dt: &DataType, constraints: &[Constraint]) -> String {
    let base = match dt {
        DataType::String(_) => {
            let mut s = "z.string()".to_owned();
            for c in constraints {
                match c.name.as_str() {
                    "min_length" => s.push_str(&format!(".min({})", constraint_value_str(c))),
                    "max_length" => s.push_str(&format!(".max({})", constraint_value_str(c))),
                    "pattern" => s.push_str(&format!(".regex(/{}/)", constraint_value_str(c))),
                    "non_empty" => s.push_str(".min(1)"),
                    _ => {}
                }
            }
            s
        }
        DataType::Int(_) | DataType::Float(_) => {
            let mut s = "z.number()".to_owned();
            for c in constraints {
                match c.name.as_str() {
                    "min" => s.push_str(&format!(".gte({})", constraint_value_str(c))),
                    "max" => s.push_str(&format!(".lte({})", constraint_value_str(c))),
                    _ => {}
                }
            }
            s
        }
        DataType::Boolean(_) => "z.boolean()".to_owned(),
        DataType::List(inner, _) => format!("z.array({})", data_type_to_zod(inner, &[])),
        DataType::Custom(name, _) => format!("{}Schema", name),
    };
    base
}

fn constraint_comment(constraints: &[Constraint]) -> String {
    let parts: Vec<String> = constraints.iter()
        .map(|c| format!("{}: {}", c.name, constraint_value_str(c)))
        .collect();
    parts.join(", ")
}
