use std::fs;
use std::path::Path;

use crate::ast::{Block, DataType, Document, ElseBranch, Expr, SpannedExpr, Statement, WorkflowDecl};
use crate::errors::{CompilerError, CompilerResult};

pub fn generate(document: &Document, project_root: &Path) -> CompilerResult<()> {
    if document.workflows.is_empty() {
        return Ok(());
    }

    let workflows_dir = project_root.join("generated").join("workflows");
    fs::create_dir_all(&workflows_dir).map_err(|e| CompilerError::IoError {
        message: format!("failed to create workflows directory: {e}"),
        span: 0..0,
    })?;

    for workflow in &document.workflows {
        let content = emit_workflow(workflow, document);
        let filename = format!("{}.ts", workflow.name);
        fs::write(workflows_dir.join(&filename), content).map_err(|e| CompilerError::IoError {
            message: format!("failed to write workflow {}: {e}", filename),
            span: workflow.span.clone(),
        })?;
    }

    // Generate index barrel
    let index = emit_index(&document.workflows);
    fs::write(workflows_dir.join("index.ts"), index).map_err(|e| CompilerError::IoError {
        message: format!("failed to write workflows/index.ts: {e}"),
        span: 0..0,
    })?;

    Ok(())
}

fn emit_index(workflows: &[WorkflowDecl]) -> String {
    let mut out = String::from("// generated/workflows/index.ts — auto-generated. Do not edit.\n\n");
    for w in workflows {
        out.push_str(&format!("export {{ {} }} from './{}.js';\n", w.name, w.name));
    }
    out
}

fn emit_workflow(w: &WorkflowDecl, document: &crate::ast::Document) -> String {
    let mut out = String::from(
        "// auto-generated by claw compile. Do not edit.\n",
    );

    // Collect tool imports used in this workflow
    let used_tools = collect_used_tools(&w.body, document);
    for tool in &used_tools {
        out.push_str(&format!("import {{ {} }} from '../tools/{}.js';\n", tool, tool));
    }

    // Collect agents used in reason{} blocks — all route through runtime/reason.ts,
    // not per-agent module files (which don't exist). C-01 fix from spec 47.
    let used_agents = collect_used_agents(&w.body);
    if !used_agents.is_empty() {
        let has_resynth = has_resynthesize_strategy(&w.body);
        if has_resynth {
            out.push_str("import { reason, judgeReason, clawReSynthesize } from '../runtime/reason.js';\n");
        } else {
            out.push_str("import { reason, judgeReason } from '../runtime/reason.js';\n");
        }
    }

    // Type imports
    let type_refs = collect_type_refs(w, document);
    if !type_refs.is_empty() {
        let type_list = type_refs.join(", ");
        out.push_str(&format!("import type {{ {} }} from '../types.js';\n", type_list));
    }

    out.push('\n');

    // Input type
    let _input_type = if w.arguments.is_empty() {
        "{}".to_owned()
    } else {
        let fields: Vec<String> = w.arguments.iter()
            .map(|a| format!("{}: {}", a.name, data_type_to_ts(&a.data_type)))
            .collect();
        format!("{{ {} }}", fields.join(", "))
    };

    let output_type = w.return_type.as_ref()
        .map(data_type_to_ts)
        .unwrap_or_else(|| "void".to_owned());

    let params: Vec<String> = w.arguments.iter()
        .map(|a| format!("{}: {}", a.name, data_type_to_ts(&a.data_type)))
        .collect();

    out.push_str(&format!(
        "export async function {}({}): Promise<{}> {{\n",
        w.name,
        params.join(", "),
        output_type,
    ));

    let mut body = String::new();
    emit_block_ts(&mut body, &w.body, 1);
    out.push_str(&body);

    out.push_str("}\n");
    out
}

fn emit_block_ts(out: &mut String, block: &Block, indent: usize) {
    for stmt in &block.statements {
        emit_statement_ts(out, stmt, indent);
    }
}

fn emit_statement_ts(out: &mut String, stmt: &Statement, indent: usize) {
    let pad = "  ".repeat(indent);

    match stmt {
        Statement::LetDecl { name, value, .. } => {
            let val = emit_expr_ts(&value.expr);
            out.push_str(&format!("{}const {} = await {};\n", pad, name, val));
        }
        Statement::Return { value, .. } => {
            let val = emit_expr_ts(&value.expr);
            out.push_str(&format!("{}return {};\n", pad, val));
        }
        Statement::ExecuteRun { agent_name, kwargs, .. } => {
            let args = emit_kwargs_ts(kwargs);
            out.push_str(&format!("{}await {}({});\n", pad, agent_name, args));
        }
        Statement::Reason { using_agent, input, goal, bind, output_type, on_fail, .. } => {
            let out_type = data_type_to_ts(output_type);
            match on_fail {
                Some(crate::ast::OnFailStrategy::Retry { max }) => {
                    // Emit a retry loop: judge the output; on rejection, re-run up to max times.
                    out.push_str(&format!(
                        "{pad}let {bind}: {out_type} | undefined;\n"
                    ));
                    out.push_str(&format!(
                        "{pad}for (let _attempt = 0; _attempt < {max}; _attempt++) {{\n"
                    ));
                    out.push_str(&format!(
                        "{pad}  const _candidate = await reason<{out_type}>({{ agent: \"{using_agent}\", input: {input}, goal: {goal:?} }});\n"
                    ));
                    out.push_str(&format!(
                        "{pad}  const _ok = await judgeReason({{ agent: \"{using_agent}\", result: _candidate, goal: {goal:?} }});\n"
                    ));
                    out.push_str(&format!(
                        "{pad}  if (_ok) {{ {bind} = _candidate; break; }}\n"
                    ));
                    out.push_str(&format!("{pad}}}\n"));
                    out.push_str(&format!(
                        "{pad}if ({bind} === undefined) throw new Error('reason: goal not achieved after {max} attempts: {goal}');\n"
                    ));
                }
                Some(crate::ast::OnFailStrategy::ReSynthesize) => {
                    // Judge first; if rejected, invoke claw synthesize and retry once.
                    out.push_str(&format!(
                        "{pad}let {bind} = await reason<{out_type}>({{ agent: \"{using_agent}\", input: {input}, goal: {goal:?} }});\n"
                    ));
                    out.push_str(&format!(
                        "{pad}if (!await judgeReason({{ agent: \"{using_agent}\", result: {bind}, goal: {goal:?} }})) {{\n"
                    ));
                    out.push_str(&format!(
                        "{pad}  await clawReSynthesize();\n"
                    ));
                    out.push_str(&format!(
                        "{pad}  {bind} = await reason<{out_type}>({{ agent: \"{using_agent}\", input: {input}, goal: {goal:?} }});\n"
                    ));
                    out.push_str(&format!("{pad}}}\n"));
                }
                None => {
                    out.push_str(&format!(
                        "{pad}const {bind} = await reason<{out_type}>({{ agent: \"{using_agent}\", input: {input}, goal: {goal:?} }});\n",
                    ));
                }
            }
        }
        Statement::IfCond { condition, if_body, else_body, .. } => {
            let cond = emit_expr_ts(&condition.expr);
            out.push_str(&format!("{}if ({}) {{\n", pad, cond));
            emit_block_ts(out, if_body, indent + 1);
            match else_body {
                Some(ElseBranch::Else(block)) => {
                    out.push_str(&format!("{}}} else {{\n", pad));
                    emit_block_ts(out, block, indent + 1);
                    out.push_str(&format!("{}}}\n", pad));
                }
                Some(ElseBranch::ElseIf(stmt)) => {
                    out.push_str(&format!("{}}} else ", pad));
                    emit_statement_ts(out, stmt, 0);
                }
                None => {
                    out.push_str(&format!("{}}}\n", pad));
                }
            }
        }
        Statement::ForLoop { item_name, iterator, body, .. } => {
            let iter = emit_expr_ts(&iterator.expr);
            out.push_str(&format!("{}for (const {} of {}) {{\n", pad, item_name, iter));
            emit_block_ts(out, body, indent + 1);
            out.push_str(&format!("{}}}\n", pad));
        }
        Statement::TryCatch { try_body, catch_name, catch_body, .. } => {
            out.push_str(&format!("{}try {{\n", pad));
            emit_block_ts(out, try_body, indent + 1);
            out.push_str(&format!("{}}} catch ({}) {{\n", pad, catch_name));
            emit_block_ts(out, catch_body, indent + 1);
            out.push_str(&format!("{}}}\n", pad));
        }
        Statement::Assert { condition, message, .. } => {
            let cond = emit_expr_ts(&condition.expr);
            let msg = message.as_deref().unwrap_or("assertion failed");
            out.push_str(&format!(
                "{}if (!({cond})) throw new Error({:?});\n",
                pad, msg,
            ));
        }
        Statement::Continue(_) => out.push_str(&format!("{}continue;\n", pad)),
        Statement::Break(_) => out.push_str(&format!("{}break;\n", pad)),
        Statement::Expression(spanned) => {
            let val = emit_expr_ts(&spanned.expr);
            out.push_str(&format!("{}await {};\n", pad, val));
        }
    }
}

fn emit_expr_ts(expr: &Expr) -> String {
    match expr {
        Expr::StringLiteral(s) => {
            // Convert ${var} interpolations to template literals
            if s.contains("${") {
                format!("`{}`", s)
            } else {
                format!("{:?}", s)
            }
        }
        Expr::IntLiteral(n) => n.to_string(),
        Expr::FloatLiteral(f) => f.to_string(),
        Expr::BoolLiteral(b) => b.to_string(),
        Expr::Identifier(name) => name.clone(),
        Expr::ArrayLiteral(items) => {
            let vals: Vec<String> = items.iter().map(|i| emit_expr_ts(&i.expr)).collect();
            format!("[{}]", vals.join(", "))
        }
        Expr::MemberAccess(obj, field) => {
            format!("{}.{}", emit_expr_ts(&obj.expr), field)
        }
        Expr::Call(name, args) => {
            let vals: Vec<String> = args.iter().map(|a| emit_expr_ts(&a.expr)).collect();
            format!("{}({})", name, vals.join(", "))
        }
        Expr::MethodCall(obj, method, args) => {
            let vals: Vec<String> = args.iter().map(|a| emit_expr_ts(&a.expr)).collect();
            format!("{}.{}({})", emit_expr_ts(&obj.expr), method, vals.join(", "))
        }
        Expr::ExecuteRun { agent_name, kwargs, .. } => {
            emit_kwargs_call(agent_name, kwargs)
        }
        Expr::DirectToolCall { tool_name, args } => {
            let entries: Vec<String> = args
                .iter()
                .map(|(k, v)| format!("{k}: {}", emit_expr_ts(&v.expr)))
                .collect();
            format!("callTool_{tool_name}({{{}}})", entries.join(", "))
        }
        Expr::BinaryOp { left, op, right } => {
            use crate::ast::BinaryOp;
            let op_str = match op {
                BinaryOp::Equal => "===",
                BinaryOp::NotEqual => "!==",
                BinaryOp::LessThan => "<",
                BinaryOp::GreaterThan => ">",
                BinaryOp::LessEq => "<=",
                BinaryOp::GreaterEq => ">=",
            };
            format!("{} {} {}", emit_expr_ts(&left.expr), op_str, emit_expr_ts(&right.expr))
        }
    }
}

fn emit_kwargs_call(fn_name: &str, kwargs: &[(String, SpannedExpr)]) -> String {
    if kwargs.is_empty() {
        return format!("{}({{}})", fn_name);
    }
    let args: Vec<String> = kwargs.iter()
        .map(|(k, v)| format!("{}: {}", k, emit_expr_ts(&v.expr)))
        .collect();
    format!("{}({{ {} }})", fn_name, args.join(", "))
}

fn emit_kwargs_ts(kwargs: &[(String, SpannedExpr)]) -> String {
    if kwargs.is_empty() {
        return "{}".to_owned();
    }
    let args: Vec<String> = kwargs.iter()
        .map(|(k, v)| format!("{}: {}", k, emit_expr_ts(&v.expr)))
        .collect();
    format!("{{ {} }}", args.join(", "))
}

fn data_type_to_ts(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => "string".to_owned(),
        DataType::Int(_) => "number".to_owned(),
        DataType::Float(_) => "number".to_owned(),
        DataType::Boolean(_) => "boolean".to_owned(),
        DataType::List(inner, _) => format!("{}[]", data_type_to_ts(inner)),
        DataType::Custom(name, _) => name.clone(),
    }
}

fn collect_used_tools(block: &Block, document: &crate::ast::Document) -> Vec<String> {
    let mut tools = Vec::new();
    collect_tools_from_block(block, document, &mut tools);
    tools.sort();
    tools.dedup();
    tools
}

fn collect_tools_from_block(block: &Block, document: &crate::ast::Document, tools: &mut Vec<String>) {
    for stmt in &block.statements {
        collect_tools_from_stmt(stmt, document, tools);
    }
}

fn collect_tools_from_stmt(stmt: &Statement, document: &crate::ast::Document, tools: &mut Vec<String>) {
    match stmt {
        Statement::LetDecl { value, .. } => {
            collect_tools_from_expr(&value.expr, document, tools);
        }
        Statement::ExecuteRun { agent_name, .. } => {
            // Only include if it's a tool (has using:), not an agent
            if document.tools.iter().any(|t| t.name == *agent_name && t.using.is_some()) {
                tools.push(agent_name.clone());
            }
        }
        Statement::IfCond { if_body, else_body, .. } => {
            collect_tools_from_block(if_body, document, tools);
            if let Some(ElseBranch::Else(block)) = else_body {
                collect_tools_from_block(block, document, tools);
            }
            if let Some(ElseBranch::ElseIf(stmt)) = else_body {
                collect_tools_from_stmt(stmt, document, tools);
            }
        }
        Statement::ForLoop { body, .. } => collect_tools_from_block(body, document, tools),
        Statement::TryCatch { try_body, catch_body, .. } => {
            collect_tools_from_block(try_body, document, tools);
            collect_tools_from_block(catch_body, document, tools);
        }
        _ => {}
    }
}

fn collect_tools_from_expr(expr: &Expr, document: &crate::ast::Document, tools: &mut Vec<String>) {
    if let Expr::ExecuteRun { agent_name, .. } = expr {
        if document.tools.iter().any(|t| t.name == *agent_name && t.using.is_some()) {
            tools.push(agent_name.clone());
        }
    }
}

fn collect_used_agents(block: &Block) -> Vec<String> {
    let mut agents = Vec::new();
    collect_agents_from_block(block, &mut agents);
    agents.sort();
    agents.dedup();
    agents
}

fn collect_agents_from_block(block: &Block, agents: &mut Vec<String>) {
    for stmt in &block.statements {
        if let Statement::Reason { using_agent, .. } = stmt {
            agents.push(using_agent.clone());
        }
    }
}

/// Returns true if any reason{} block in this workflow uses `on_fail: re_synthesize`,
/// which requires `clawReSynthesize` to be imported.
fn has_resynthesize_strategy(block: &Block) -> bool {
    block.statements.iter().any(|stmt| {
        matches!(
            stmt,
            Statement::Reason { on_fail: Some(crate::ast::OnFailStrategy::ReSynthesize), .. }
        )
    })
}

fn collect_type_refs(w: &WorkflowDecl, document: &crate::ast::Document) -> Vec<String> {
    let mut types = Vec::new();

    if let Some(rt) = &w.return_type {
        if let DataType::Custom(name, _) = rt {
            types.push(name.clone());
        }
    }

    for arg in &w.arguments {
        if let DataType::Custom(name, _) = &arg.data_type {
            types.push(name.clone());
        }
    }

    types.sort();
    types.dedup();
    // Only include types that are actually declared in the document
    types.retain(|t| document.types.iter().any(|td| &td.name == t));
    types
}
