// src/codegen/typescript.rs
// Generates generated/claw/index.ts — a self-contained BAML-style TypeScript client.
// No @claw/sdk dependency. Only imports: node built-ins + zod.
// Each workflow compiles to a typed, directly callable exported function.
// See specs/41-BAML-Style-TypeScript-Codegen.md

use std::collections::HashSet;

use crate::ast::{
    AgentDecl, Block, Constraint, DataType, Document, Expr, SettingValue, SpannedExpr, Statement,
    ToolDecl, TypeDecl, TypeField,
};
use crate::errors::{CompilerError, CompilerResult};

pub(super) fn generate(document: &Document) -> CompilerResult<String> {
    let mut out = String::new();

    // 1. File header + imports
    out.push_str(HEADER);
    out.push_str("\n\n");

    // 2. Type interfaces
    for t in &document.types {
        out.push_str(&render_interface(t));
        out.push_str("\n\n");
    }

    // 3. Zod schemas
    for t in &document.types {
        out.push_str(&render_schema(t)?);
        out.push_str("\n\n");
    }

    // 4. Tool handlers
    out.push_str(&emit_tool_handlers(document));
    out.push_str("\n");

    // 5. Agent runners
    out.push_str(&emit_agent_runners(document));

    // 6. Exported workflow functions
    for wf in &document.workflows {
        out.push_str(&render_workflow(wf, document)?);
        out.push_str("\n\n");
    }

    // 7. CLI entry guard
    out.push_str(&emit_cli_entry(document));

    Ok(out)
}

// ─── Header ───────────────────────────────────────────────────────────────────

const HEADER: &str = r#"// generated/claw/index.ts
// AUTO-GENERATED by claw build --lang ts — DO NOT EDIT
// Run:    npx tsx generated/claw/index.ts <WorkflowName> --arg key=value
// Import: import { WorkflowName } from "./generated/claw/index.js"
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs/promises";
import { z } from "zod";"#;

// ─── Type Interfaces ──────────────────────────────────────────────────────────

fn render_interface(declaration: &TypeDecl) -> String {
    let fields = declaration
        .fields
        .iter()
        .map(|field| format!("    {}: {};", field.name, render_ts_type(&field.data_type)))
        .collect::<Vec<_>>()
        .join("\n");
    format!("export interface {} {{\n{}\n}}", declaration.name, fields)
}

// ─── Zod Schemas ─────────────────────────────────────────────────────────────

fn render_schema(declaration: &TypeDecl) -> CompilerResult<String> {
    let fields = declaration
        .fields
        .iter()
        .map(render_schema_field)
        .collect::<CompilerResult<Vec<_>>>()?
        .join("\n");
    Ok(format!(
        "export const {}Schema: z.ZodType<{}> = z.object({{\n{}\n}}).strict();",
        declaration.name, declaration.name, fields
    ))
}

fn render_schema_field(field: &TypeField) -> CompilerResult<String> {
    let schema = apply_constraints(render_zod_type(&field.data_type), &field.constraints)?;
    Ok(format!("    {}: {},", field.name, schema))
}

// ─── Tool Handlers ────────────────────────────────────────────────────────────

fn emit_tool_handlers(document: &Document) -> String {
    let mut handlers: Vec<String> = Vec::new();
    let mut cases: Vec<String> = Vec::new();

    for tool in &document.tools {
        let handler = emit_tool_handler(tool);
        let args_type = render_tool_args_type(tool);
        handlers.push(handler);
        cases.push(format!(
            "    case \"{name}\": return callTool_{name}(input as {args_type});",
            name = tool.name,
            args_type = args_type,
        ));
    }

    let dispatch = if cases.is_empty() {
        r#"async function callTool(name: string, _input: unknown): Promise<unknown> {
  throw { code: "E-RUN99", message: `unknown tool: ${name}` };
}"#.to_owned()
    } else {
        format!(
            r#"async function callTool(name: string, input: unknown): Promise<unknown> {{
  switch (name) {{
{}
    default: throw {{ code: "E-RUN99", message: `unknown tool: ${{name}}` }};
  }}
}}"#,
            cases.join("\n")
        )
    };

    if handlers.is_empty() {
        format!("{}\n", dispatch)
    } else {
        format!("{}\n\n{}\n", handlers.join("\n\n"), dispatch)
    }
}

fn render_tool_args_type(tool: &ToolDecl) -> String {
    if tool.arguments.is_empty() {
        "Record<string, never>".to_owned()
    } else {
        let fields: Vec<String> = tool
            .arguments
            .iter()
            .map(|a| format!("{}: {}", a.name, render_ts_type(&a.data_type)))
            .collect();
        format!("{{ {} }}", fields.join("; "))
    }
}

fn emit_tool_handler(tool: &ToolDecl) -> String {
    let args_type = render_tool_args_type(tool);
    let arg_names: Vec<&str> = tool.arguments.iter().map(|a| a.name.as_str()).collect();

    let using = tool.using.as_ref();

    let body = if let Some(invoke_path) = &tool.invoke_path {
        if invoke_path.starts_with("module(") {
            emit_module_tool_handler(tool, invoke_path, &arg_names)
        } else {
            format!(
                r#"  throw {{ code: "E-RUN99", message: "tool '{name}': unsupported invoke path" }};"#,
                name = tool.name,
            )
        }
    } else if using.is_some() {
        // using: baml(...) stub
        let using_str = match using {
            Some(crate::ast::UsingExpr::Baml(name)) => {
                format!("baml tool '{}' requires running `npx @boundaryml/baml-cli generate` first", name)
            }
            _ => format!("tool '{}': no handler configured", tool.name),
        };
        format!(r#"  throw {{ code: "E-RUN99", message: "{}" }};"#, using_str)
    } else {
        format!(
            r#"  throw {{ code: "E-RUN99", message: "tool '{name}': no handler configured" }};"#,
            name = tool.name,
        )
    };

    format!(
        "async function callTool_{name}(args: {args_type}): Promise<unknown> {{\n{body}\n}}",
        name = tool.name,
        args_type = args_type,
        body = body,
    )
}

fn emit_module_tool_handler(_tool: &ToolDecl, invoke_path: &str, arg_names: &[&str]) -> String {
    // Parse: module("scripts/search").function("run")
    let parts: Vec<&str> = invoke_path.splitn(2, ").function(").collect();
    let module_path = if parts[0].len() > 8 {
        let s = &parts[0][8..]; // strip 'module("'
        &s[..s.rfind('"').unwrap_or(s.len())]
    } else {
        "scripts/stub"
    };
    let fn_name = if parts.len() > 1 && parts[1].len() > 1 {
        let s = &parts[1][1..]; // strip leading '"'
        &s[..s.rfind('"').unwrap_or(s.len())]
    } else {
        "run"
    };

    let arg_list = arg_names
        .iter()
        .map(|n| format!("args.{n}"))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"  const modPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../{module}.js");
  const real = await fs.realpath(modPath);
  const mod = await import(new URL(real, "file://").href);
  return await (mod as {{ {fn}: (...args: unknown[]) => Promise<unknown> }}).{fn}({arg_list});"#,
        module = module_path,
        fn = fn_name,
        arg_list = arg_list,
    )
}

// ─── Agent Runners ────────────────────────────────────────────────────────────

fn emit_agent_runners(document: &Document) -> String {
    let mut out = String::new();
    for agent in &document.agents {
        let (provider, model) = resolve_client(agent, document);
        let is_local = provider == "local" || provider == "ollama";
        let model_str = model.trim_start_matches("local.").to_owned();

        let system_prompt = agent
            .system_prompt
            .as_deref()
            .unwrap_or("")
            .replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n");

        let max_steps: i64 = agent
            .settings
            .entries
            .iter()
            .find(|e| e.name == "max_steps")
            .and_then(|e| {
                if let SettingValue::Int(n) = e.value {
                    Some(n)
                } else {
                    None
                }
            })
            .unwrap_or(10);

        let temperature: f64 = agent
            .settings
            .entries
            .iter()
            .find(|e| e.name == "temperature")
            .and_then(|e| match e.value {
                SettingValue::Float(f) => Some(f),
                SettingValue::Int(n) => Some(n as f64),
                _ => None,
            })
            .unwrap_or(1.0);

        let tools_filter = if agent.tools.is_empty() {
            emit_tools_array(document, None)
        } else {
            emit_tools_array(document, Some(&agent.tools))
        };

        let fn_name = format!("runAgent_{}", agent.name);

        let runner = if is_local {
            emit_ts_ollama_runner(&fn_name, &system_prompt, &model_str, max_steps, temperature, &tools_filter)
        } else {
            emit_ts_anthropic_runner(&fn_name, &system_prompt, &model_str, max_steps, temperature, &tools_filter)
        };

        out.push_str(&runner);
        out.push_str("\n\n");
    }
    out
}

fn emit_tools_array(document: &Document, filter: Option<&[String]>) -> String {
    let tools: Vec<&crate::ast::ToolDecl> = document
        .tools
        .iter()
        .filter(|t| {
            filter
                .map(|f| f.contains(&t.name))
                .unwrap_or(true)
        })
        .collect();

    if tools.is_empty() {
        return "[]".to_owned();
    }

    let entries: Vec<String> = tools
        .iter()
        .map(|tool| {
            let props: Vec<String> = tool
                .arguments
                .iter()
                .map(|a| format!("          \"{}\": {}", a.name, ts_json_schema_for(&a.data_type)))
                .collect();
            let required: Vec<String> = tool
                .arguments
                .iter()
                .map(|a| format!("\"{}\"", a.name))
                .collect();
            format!(
                r#"  {{
    name: "{name}",
    description: "Tool {name}",
    inputSchema: {{
      type: "object" as const,
      properties: {{
{props}
      }},
      required: [{req}]
    }}
  }}"#,
                name = tool.name,
                props = props.join(",\n"),
                req = required.join(", "),
            )
        })
        .collect();

    format!("[\n{}\n]", entries.join(",\n"))
}

fn ts_json_schema_for(dt: &DataType) -> String {
    match dt {
        DataType::String(_) => "{ type: \"string\" as const }".to_owned(),
        DataType::Int(_) => "{ type: \"integer\" as const }".to_owned(),
        DataType::Float(_) => "{ type: \"number\" as const }".to_owned(),
        DataType::Boolean(_) => "{ type: \"boolean\" as const }".to_owned(),
        DataType::List(inner, _) => format!(
            "{{ type: \"array\" as const, items: {} }}",
            ts_json_schema_for(inner)
        ),
        DataType::Custom(name, _) => format!(
            "{{ type: \"object\" as const, description: \"{}\" }}",
            name
        ),
    }
}

fn emit_ts_anthropic_runner(
    fn_name: &str,
    system_prompt: &str,
    model: &str,
    max_steps: i64,
    temperature: f64,
    tools_array: &str,
) -> String {
    format!(
        r#"async function {fn_name}(task: string): Promise<string> {{
  if (!process.env.ANTHROPIC_API_KEY) {{
    throw {{ code: "E-RT03", message: "ANTHROPIC_API_KEY not set\n  export ANTHROPIC_API_KEY=sk-ant-..." }};
  }}
  const agentTools: Array<{{ name: string; description: string; inputSchema: unknown }}> = {tools_array};
  const messages: Array<{{ role: string; content: unknown }}> = [{{ role: "user", content: task }}];
  let steps = 0;

  while (steps < {max_steps}) {{
    steps++;
    const resp = await fetch("https://api.anthropic.com/v1/messages", {{
      method: "POST",
      headers: {{
        "x-api-key": process.env.ANTHROPIC_API_KEY as string,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      }},
      body: JSON.stringify({{
        model: "{model}",
        system: "{system_prompt}",
        messages,
        tools: agentTools.length > 0 ? agentTools.map(t => ({{
          name: t.name,
          description: t.description,
          input_schema: t.inputSchema,
        }})) : undefined,
        max_tokens: 4096,
        temperature: {temperature},
      }}),
    }});
    if (!resp.ok) {{
      const text = await resp.text();
      throw {{ code: "E-RUN04", message: `Anthropic API error ${{resp.status}}: ${{text}}` }};
    }}
    const data = await resp.json() as {{
      stop_reason: string;
      content: Array<{{ type: string; text?: string; id?: string; name?: string; input?: unknown }}>;
    }};

    if (data.stop_reason === "end_turn") {{
      return data.content.find(b => b.type === "text")?.text ?? "";
    }}

    if (data.stop_reason === "tool_use") {{
      const toolUseBlocks = data.content.filter(b => b.type === "tool_use");
      messages.push({{ role: "assistant", content: data.content }});
      const toolResults: unknown[] = [];
      for (const tu of toolUseBlocks) {{
        let resultContent: string;
        try {{
          resultContent = JSON.stringify(await callTool(tu.name as string, tu.input));
        }} catch (e: unknown) {{
          const err = e as {{ message?: string }};
          resultContent = `Error: ${{err.message ?? String(e)}}`;
        }}
        toolResults.push({{ type: "tool_result", tool_use_id: tu.id, content: resultContent }});
      }}
      messages.push({{ role: "user", content: toolResults }});
      continue;
    }}
    break;
  }}

  return `Agent {fn_name} reached max_steps ({max_steps}) without finishing.`;
}}"#,
        fn_name = fn_name,
        tools_array = tools_array,
        max_steps = max_steps,
        model = model,
        system_prompt = system_prompt,
        temperature = temperature,
    )
}

fn emit_ts_ollama_runner(
    fn_name: &str,
    system_prompt: &str,
    model: &str,
    max_steps: i64,
    temperature: f64,
    tools_array: &str,
) -> String {
    format!(
        r#"async function {fn_name}(task: string): Promise<string> {{
  const host = process.env.OLLAMA_HOST ?? "http://localhost:11434";
  const agentTools: Array<{{ name: string; description: string; inputSchema: unknown }}> = {tools_array};
  const messages: Array<{{ role: string; content: string | null; tool_calls?: unknown[] }}> = [
    {{ role: "system", content: "{system_prompt}" }},
    {{ role: "user", content: task }},
  ];
  let steps = 0;

  while (steps < {max_steps}) {{
    steps++;
    const resp = await fetch(`${{host}}/v1/chat/completions`, {{
      method: "POST",
      headers: {{ "content-type": "application/json" }},
      body: JSON.stringify({{
        model: "{model}",
        messages,
        tools: agentTools.length > 0 ? agentTools.map(t => ({{
          type: "function",
          function: {{ name: t.name, description: t.description, parameters: t.inputSchema }},
        }})) : undefined,
        stream: false,
        temperature: {temperature},
      }}),
    }});
    if (!resp.ok) {{
      const text = await resp.text();
      throw {{ code: "E-RUN04", message: `Ollama error ${{resp.status}}: ${{text}}\n  hint: start Ollama with \`ollama serve\`` }};
    }}
    const data = await resp.json() as {{
      choices: Array<{{
        finish_reason: string;
        message: {{ content: string | null; tool_calls?: Array<{{ id: string; function: {{ name: string; arguments: string | unknown }} }}> }};
      }}>;
    }};
    const choice = data.choices?.[0];
    if (!choice) break;

    if (choice.finish_reason === "stop" || choice.finish_reason === "length") {{
      return choice.message?.content ?? "";
    }}

    if (choice.finish_reason === "tool_calls") {{
      const toolCalls = choice.message?.tool_calls ?? [];
      messages.push({{ role: "assistant", content: choice.message?.content ?? null, tool_calls: toolCalls }});
      for (const tc of toolCalls) {{
        let resultContent: string;
        try {{
          const tcArgs = typeof tc.function.arguments === "string"
            ? JSON.parse(tc.function.arguments)
            : tc.function.arguments;
          resultContent = JSON.stringify(await callTool(tc.function.name, tcArgs));
        }} catch (e: unknown) {{
          const err = e as {{ message?: string }};
          resultContent = `Error: ${{err.message ?? String(e)}}`;
        }}
        messages.push({{ role: "tool", tool_call_id: tc.id, content: resultContent }});
      }}
      continue;
    }}
    break;
  }}

  return `Agent {fn_name} reached max_steps ({max_steps}) without finishing.`;
}}"#,
        fn_name = fn_name,
        tools_array = tools_array,
        max_steps = max_steps,
        system_prompt = system_prompt,
        model = model,
        temperature = temperature,
    )
}

fn resolve_client(agent: &AgentDecl, document: &Document) -> (String, String) {
    if let Some(client_name) = &agent.client {
        if let Some(c) = document.clients.iter().find(|c| &c.name == client_name) {
            return (c.provider.clone(), c.model.clone());
        }
    }
    if let Some(c) = document.clients.first() {
        return (c.provider.clone(), c.model.clone());
    }
    ("anthropic".to_owned(), "claude-haiku-4-5-20251001".to_owned())
}

// ─── Workflow Functions ───────────────────────────────────────────────────────

fn render_workflow(wf: &crate::ast::WorkflowDecl, document: &Document) -> CompilerResult<String> {
    let args_type = if wf.arguments.is_empty() {
        "Record<string, never>".to_owned()
    } else {
        let fields: Vec<String> = wf
            .arguments
            .iter()
            .map(|a| format!("{}: {}", a.name, render_ts_type(&a.data_type)))
            .collect();
        format!("{{ {} }}", fields.join("; "))
    };

    let return_ts = wf
        .return_type
        .as_ref()
        .map(render_ts_type)
        .unwrap_or_else(|| "unknown".to_owned());

    let wf_arg_names: HashSet<String> = wf.arguments.iter().map(|a| a.name.clone()).collect();
    let body = render_workflow_body(&wf.body, &wf_arg_names, document)?;

    // Artifact saving block
    let artifact_block = if let Some(artifact) = &wf.artifact {
        let expanded_path = ts_expand_path(&artifact.path, &wf_arg_names);
        if artifact.format == "image" {
            format!(
                r#"  const _srcPath: string = (result as Record<string, unknown>)?.path as string ?? "";
  const _artifactPath = path.resolve({expanded_path}.replace(/^~/, process.env.HOME ?? "~"));
  await fs.mkdir(path.dirname(_artifactPath), {{ recursive: true }});
  if (_srcPath && _srcPath !== _artifactPath) {{
    const {{ copyFile }} = await import("fs/promises");
    await copyFile(_srcPath, _artifactPath);
  }}
  process.stderr.write(`[claw] artifact saved → ${{_artifactPath}}\n`);
"#,
            )
        } else {
            let serialize = match artifact.format.as_str() {
                "json" => "JSON.stringify(result, null, 2)".to_owned(),
                "markdown" | "text" => "(result as Record<string, unknown>)?.content as string ?? JSON.stringify(result, null, 2)".to_owned(),
                "html" => "(result as Record<string, unknown>)?.content as string ?? `<pre>${JSON.stringify(result, null, 2)}</pre>`".to_owned(),
                _ => "JSON.stringify(result, null, 2)".to_owned(),
            };
            format!(
                r#"  const _artifactPath = path.resolve({expanded_path}.replace(/^~/, process.env.HOME ?? "~"));
  await fs.mkdir(path.dirname(_artifactPath), {{ recursive: true }});
  await fs.writeFile(_artifactPath, {serialize}, "utf8");
  process.stderr.write(`[claw] artifact saved → ${{_artifactPath}}\n`);
"#,
            )
        }
    } else {
        String::new()
    };

    Ok(format!(
        "export async function {name}(args: {args_type}): Promise<{ret}> {{\n{body}{artifact}  return result;\n}}",
        name = wf.name,
        args_type = args_type,
        ret = return_ts,
        body = body,
        artifact = artifact_block,
    ))
}

fn ts_expand_path(path: &str, wf_arg_names: &HashSet<String>) -> String {
    // Convert ~/Desktop/${topic}.json → `~/Desktop/${args.topic}.json` TypeScript template literal
    let mut result = String::with_capacity(path.len() + 8);
    result.push('`');
    let mut chars = path.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '$' && chars.peek() == Some(&'{') {
            chars.next();
            let mut var_name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' { break; }
                var_name.push(c2);
            }
            if wf_arg_names.contains(&var_name) {
                result.push_str(&format!("${{args.{var_name}}}"));
            } else {
                result.push_str(&format!("${{{var_name}}}"));
            }
        } else if c == '`' {
            result.push_str("\\`");
        } else {
            result.push(c);
        }
    }
    result.push('`');
    result
}

fn render_workflow_body(
    block: &Block,
    wf_arg_names: &HashSet<String>,
    document: &Document,
) -> CompilerResult<String> {
    let mut lines: Vec<String> = Vec::new();
    // Track local let-bound vars
    let mut local_vars: HashSet<String> = HashSet::new();

    for stmt in &block.statements {
        let compiled = compile_ts_statement(stmt, wf_arg_names, &local_vars, document)?;
        lines.push(compiled);
        // Track newly bound variables
        if let Statement::LetDecl { name, .. } = stmt {
            local_vars.insert(name.clone());
        }
    }

    Ok(lines.join("\n"))
}

fn compile_ts_statement(
    stmt: &Statement,
    wf_arg_names: &HashSet<String>,
    _local_vars: &HashSet<String>,
    _document: &Document,
) -> CompilerResult<String> {
    match stmt {
        Statement::LetDecl { name, value, explicit_type, .. } => {
            match &value.expr {
                Expr::ExecuteRun { agent_name, kwargs, require_type } => {
                    let task_ts = extract_task_ts(kwargs, wf_arg_names);
                    Ok(emit_ts_execute_and_bind(name, agent_name, &task_ts, require_type.as_ref()))
                }
                Expr::DirectToolCall { tool_name, args } => {
                    Ok(emit_ts_direct_tool_call(name, tool_name, args, explicit_type.as_ref(), wf_arg_names))
                }
                _ => {
                    let val = expr_to_ts(&value.expr, wf_arg_names);
                    Ok(format!("  const {name} = {val};\n"))
                }
            }
        }

        Statement::ExecuteRun { agent_name, kwargs, require_type, .. } => {
            let task_ts = extract_task_ts(kwargs, wf_arg_names);
            Ok(emit_ts_execute_and_bind("_", agent_name, &task_ts, require_type.as_ref()))
        }

        Statement::Return { value, .. } => match &value.expr {
            Expr::Identifier(name) => Ok(format!("  const result = {name};\n")),
            Expr::ExecuteRun { agent_name, kwargs, require_type } => {
                Ok(emit_ts_execute_and_bind("result", agent_name, &extract_task_ts(kwargs, wf_arg_names), require_type.as_ref()))
            }
            Expr::DirectToolCall { tool_name, args } => {
                Ok(emit_ts_direct_tool_call("result", tool_name, args, None, wf_arg_names))
            }
            other => {
                let val = expr_to_ts(other, wf_arg_names);
                Ok(format!("  const result = {val};\n"))
            }
        },

        Statement::Reason { using_agent, input, goal, bind, output_type, .. } => {
            let escaped_goal = goal.replace('"', "\\\"");
            let task_ts = if input.is_empty() || input == "_" {
                format!("\"{}\"", escaped_goal)
            } else {
                format!(
                    "`Context:\\n${{JSON.stringify({input}, null, 2)}}\\n\\nGoal: {escaped_goal}`"
                )
            };
            Ok(emit_ts_execute_and_bind(bind, using_agent, &task_ts, Some(output_type)))
        }

        // Unsupported at TypeScript level in v1
        Statement::ForLoop { .. }
        | Statement::IfCond { .. }
        | Statement::TryCatch { .. }
        | Statement::Assert { .. }
        | Statement::Continue(_)
        | Statement::Break(_)
        | Statement::Expression(_) => {
            // emit as a comment — semantic analysis already validated these
            Ok("  // [unsupported statement type in --lang ts v1]\n".to_owned())
        }
    }
}

fn emit_ts_execute_and_bind(
    bind: &str,
    agent_name: &str,
    task_ts: &str,
    require_type: Option<&DataType>,
) -> String {
    let raw_var = if bind == "_" {
        "_rawOutput".to_owned()
    } else {
        format!("_raw_{bind}")
    };

    let call_line = format!(
        "  const {raw_var} = await runAgent_{agent}({task});\n",
        raw_var = raw_var,
        agent = agent_name,
        task = task_ts,
    );

    match require_type {
        Some(DataType::Custom(type_name, _)) => {
            let bind_line = if bind == "_" {
                String::new()
            } else {
                format!("  let {bind}: {type_name};\n")
            };
            let assign_target = if bind == "_" {
                format!("const _{bind}parsed")
            } else {
                bind.to_owned()
            };
            format!(
                "{call_line}{bind_line}  try {{\n    {assign} = {schema}.parse(typeof {raw_var} === \"string\" ? JSON.parse({raw_var}) : {raw_var});\n  }} catch {{\n    throw {{ code: \"E-RUN03\", message: `type validation failed for {type_name}\\n  got: ${{{raw_var}}}` }};\n  }}\n",
                call_line = call_line,
                bind_line = bind_line,
                assign = assign_target,
                schema = format!("{type_name}Schema"),
                raw_var = raw_var,
                type_name = type_name,
            )
        }
        _ => {
            if bind == "_" {
                call_line
            } else {
                format!("{call_line}  const {bind} = {raw_var};\n")
            }
        }
    }
}

/// Emits a direct (no-LLM) tool call: `const bind = await callTool_X({arg: val, ...})`
/// followed by optional Zod parse if the explicit type is a custom type.
fn emit_ts_direct_tool_call(
    bind: &str,
    tool_name: &str,
    args: &[(String, SpannedExpr)],
    explicit_type: Option<&DataType>,
    wf_arg_names: &HashSet<String>,
) -> String {
    let obj_entries: Vec<String> = args
        .iter()
        .map(|(k, v)| format!("{k}: {}", expr_to_ts(&v.expr, wf_arg_names)))
        .collect();
    let obj_ts = format!("{{{}}}", obj_entries.join(", "));

    let raw_var = format!("_raw_{bind}");
    let call_line = format!("  const {raw_var} = await callTool_{tool_name}({obj_ts});\n");

    match explicit_type {
        Some(DataType::Custom(type_name, _)) => {
            let schema = format!("{type_name}Schema");
            let parse = format!(
                "  const {bind} = {schema}.parse(typeof {raw_var} === \"string\" ? JSON.parse({raw_var}) : {raw_var});\n"
            );
            format!("{call_line}{parse}")
        }
        _ => format!("{call_line}  const {bind} = {raw_var};\n"),
    }
}

fn extract_task_ts(kwargs: &[(String, SpannedExpr)], wf_arg_names: &HashSet<String>) -> String {
    for (key, val) in kwargs {
        if key == "task" {
            return expr_to_ts_task(&val.expr, wf_arg_names);
        }
    }
    "\"<no task>\"".to_owned()
}

fn expr_to_ts_task(expr: &Expr, wf_arg_names: &HashSet<String>) -> String {
    match expr {
        Expr::Identifier(name) => {
            if wf_arg_names.contains(name.as_str()) {
                format!("args.{name}")
            } else {
                name.clone()
            }
        }
        Expr::StringLiteral(s) => {
            // Convert to TypeScript template literal, substituting ${name} → ${args.name} for wf args
            let inner = replace_template_vars_for_ts(s, wf_arg_names);
            format!("`{inner}`")
        }
        _ => "\"\"".to_owned(),
    }
}

fn replace_template_vars_for_ts(s: &str, wf_arg_names: &HashSet<String>) -> String {
    let mut result = String::with_capacity(s.len() + 16);
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '$' && chars.peek() == Some(&'{') {
            chars.next(); // consume '{'
            let mut var_name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
                var_name.push(c2);
            }
            if wf_arg_names.contains(&var_name) {
                result.push_str(&format!("${{args.{var_name}}}"));
            } else {
                result.push_str(&format!("${{{var_name}}}"));
            }
        } else if c == '`' {
            result.push_str("\\`"); // escape backtick inside TS template literal
        } else {
            result.push(c);
        }
    }
    result
}

fn expr_to_ts(expr: &Expr, wf_arg_names: &HashSet<String>) -> String {
    match expr {
        Expr::StringLiteral(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        Expr::IntLiteral(n) => n.to_string(),
        Expr::FloatLiteral(f) => f.to_string(),
        Expr::BoolLiteral(b) => b.to_string(),
        Expr::Identifier(name) => {
            if wf_arg_names.contains(name.as_str()) {
                format!("args.{name}")
            } else {
                name.clone()
            }
        }
        Expr::MemberAccess(target, field) => {
            let target_ts = expr_to_ts(&target.expr, wf_arg_names);
            format!("{target_ts}.{field}")
        }
        Expr::DirectToolCall { tool_name, .. } => {
            format!("undefined /* call {tool_name}(...) must be used in a let binding */")
        }
        _ => "undefined".to_owned(),
    }
}

// ─── CLI Entry Guard ──────────────────────────────────────────────────────────

fn emit_cli_entry(document: &Document) -> String {
    let workflow_list: Vec<String> = document
        .workflows
        .iter()
        .map(|wf| {
            let req_args: Vec<String> = wf
                .arguments
                .iter()
                .map(|a| format!("\"{}\"", a.name))
                .collect();
            let return_type = match &wf.return_type {
                Some(DataType::Custom(name, _)) => format!("\"{}\"", name),
                Some(_) => "\"unknown\"".to_owned(),
                None => "null".to_owned(),
            };
            format!(
                "    {{ name: \"{name}\", requiredArgs: [{args}], returnType: {ret} }}",
                name = wf.name,
                args = req_args.join(", "),
                ret = return_type,
            )
        })
        .collect();

    let cases: Vec<String> = document
        .workflows
        .iter()
        .map(|wf| {
            let cast = if wf.arguments.is_empty() {
                "cliArgs as Record<string, never>".to_owned()
            } else {
                let fields: Vec<String> = wf
                    .arguments
                    .iter()
                    .map(|a| format!("{}: string", a.name))
                    .collect();
                format!("cliArgs as {{ {} }}", fields.join("; "))
            };
            format!(
                "        case \"{name}\": result = await {name}({cast}); break;",
                name = wf.name,
                cast = cast,
            )
        })
        .collect();

    let default_case = if document.workflows.is_empty() {
        "        // no workflows declared".to_owned()
    } else {
        "        default: process.stderr.write(JSON.stringify({ error: `workflow \"${workflowArg}\" not found`, code: \"E-RUN01\" }) + \"\\n\"); process.exit(1);".to_owned()
    };

    format!(
        r#"if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {{
  const [,, workflowArg, ...rawArgs] = process.argv;

  if (!workflowArg || workflowArg === "--list") {{
    const workflows = [
{}
    ];
    process.stdout.write(JSON.stringify(workflows) + "\n");
    process.exit(0);
  }}

  function parseArgs(raw: string[]): Record<string, string> {{
    const out: Record<string, string> = {{}};
    for (let i = 0; i < raw.length; i++) {{
      if (raw[i] === "--arg" && i + 1 < raw.length) {{
        const eq = raw[++i].indexOf("=");
        if (eq !== -1) out[raw[i].slice(0, eq)] = raw[i].slice(eq + 1);
      }}
    }}
    return out;
  }}

  const cliArgs = parseArgs(rawArgs);
  (async () => {{
    try {{
      let result: unknown;
      switch (workflowArg) {{
{}
{}
      }}
      process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    }} catch (err: unknown) {{
      const e = err as {{ message?: string; code?: string }};
      process.stderr.write(JSON.stringify({{ error: e.message ?? String(err), code: e.code ?? "E-RUN99" }}) + "\n");
      process.exit(1);
    }}
  }})();
}}"#,
        workflow_list.join(",\n"),
        cases.join("\n"),
        default_case,
    )
}

// ─── Shared Helpers ───────────────────────────────────────────────────────────

fn render_ts_type(data_type: &DataType) -> String {
    match data_type {
        DataType::String(_) => "string".to_owned(),
        DataType::Int(_) | DataType::Float(_) => "number".to_owned(),
        DataType::Boolean(_) => "boolean".to_owned(),
        DataType::List(inner, _) => format!("{}[]", render_ts_type(inner)),
        DataType::Custom(name, _) => name.clone(),
    }
}

fn render_zod_type(data_type: &DataType) -> String {
    match data_type {
        DataType::String(_) => "z.string()".to_owned(),
        DataType::Int(_) => "z.number().int()".to_owned(),
        DataType::Float(_) => "z.number()".to_owned(),
        DataType::Boolean(_) => "z.boolean()".to_owned(),
        DataType::List(inner, _) => format!("z.array({})", render_zod_type(inner)),
        DataType::Custom(name, _) => format!("{name}Schema"),
    }
}

fn apply_constraints(base: String, constraints: &[Constraint]) -> CompilerResult<String> {
    let mut schema = base;
    for constraint in constraints {
        schema = match constraint.name.as_str() {
            "min" => format!("{schema}.min({})", render_numeric_constraint_value(constraint)?),
            "max" => format!("{schema}.max({})", render_numeric_constraint_value(constraint)?),
            "regex" => format!("{schema}.regex({})", render_regex_constraint_value(constraint)?),
            other => {
                return Err(CompilerError::UnsupportedConstraint {
                    name: other.to_owned(),
                    span: constraint.span.clone(),
                })
            }
        };
    }
    Ok(schema)
}

fn render_numeric_constraint_value(constraint: &Constraint) -> CompilerResult<String> {
    match &constraint.value.expr {
        Expr::IntLiteral(value) => Ok(value.to_string()),
        Expr::FloatLiteral(value) => Ok(trim_float(*value)),
        _ => Err(CompilerError::InvalidConstraintValue {
            name: constraint.name.clone(),
            expected: "a numeric literal".to_owned(),
            span: constraint.span.clone(),
        }),
    }
}

fn render_regex_constraint_value(constraint: &Constraint) -> CompilerResult<String> {
    match &constraint.value.expr {
        Expr::StringLiteral(pattern) => Ok(format!("new RegExp({pattern:?})")),
        _ => Err(CompilerError::InvalidConstraintValue {
            name: constraint.name.clone(),
            expected: "a string literal".to_owned(),
            span: constraint.span.clone(),
        }),
    }
}

fn trim_float(value: f64) -> String {
    let mut rendered = value.to_string();
    if rendered.ends_with(".0") {
        rendered.truncate(rendered.len() - 2);
    }
    rendered
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::generate as generate_ts;
    use crate::ast::{
        AgentDecl, AgentSetting, AgentSettings, Block, ClientDecl, Constraint, DataType, Document,
        Expr, SettingValue, Span, SpannedExpr, Statement, ToolDecl, TypeDecl, TypeField,
        WorkflowDecl,
    };

    fn spanned(expr: Expr, span: Span) -> SpannedExpr {
        SpannedExpr { expr, span }
    }

    #[test]
    fn emits_baml_style_self_contained_file() {
        let output = generate_ts(&valid_document()).unwrap();

        // Must NOT reference the old SDK gateway
        assert!(!output.contains("@claw/sdk"), "must not import @claw/sdk");
        assert!(!output.contains("ClawClient"), "must not reference ClawClient");
        assert!(!output.contains("executeWorkflow"), "must not call executeWorkflow");

        // Must contain node built-in imports
        assert!(output.contains("from \"node:url\""), "must import from node:url");
        assert!(output.contains("from \"zod\""), "must import zod");

        // Must export typed workflow function
        assert!(output.contains("export async function AnalyzeCompetitors"));
        assert!(output.contains(": Promise<SearchResult>"));

        // Must have agent runner
        assert!(output.contains("async function runAgent_Researcher"));

        // Must have CLI entry guard
        assert!(output.contains("fileURLToPath(import.meta.url)"));
        assert!(output.contains("--list"));
    }

    #[test]
    fn lowers_field_constraints_into_zod_validators() {
        let output = generate_ts(&valid_document()).unwrap();
        assert!(output.contains(
            r#"z.string().regex(new RegExp("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$"))"#
        ));
        assert!(output.contains("z.number().int().min(18)"));
        assert!(output.contains("z.number().min(0)"));
    }

    #[test]
    fn emits_typed_interfaces_and_schemas() {
        let output = generate_ts(&valid_document()).unwrap();

        assert!(output.contains("export interface SearchResult {"));
        assert!(output.contains("url: string;"));
        assert!(output.contains("export const SearchResultSchema"));
        assert!(output.contains("z.object({"));
        assert!(output.contains("}).strict();"));
    }

    #[test]
    fn emits_typed_tool_handler() {
        let output = generate_ts(&valid_document()).unwrap();

        assert!(output.contains("async function callTool_WebSearch(args:"));
        assert!(output.contains("callTool("));
        assert!(output.contains("\"E-RUN99\""));
    }

    #[test]
    fn emits_workflow_calls_run_agent() {
        let output = generate_ts(&valid_document()).unwrap();

        assert!(output.contains("runAgent_Researcher("));
        assert!(output.contains("SearchResultSchema.parse("));
        assert!(output.contains("\"E-RUN03\""));
    }

    #[test]
    fn emits_cli_entry_with_workflow_list() {
        let output = generate_ts(&valid_document()).unwrap();

        assert!(output.contains("\"AnalyzeCompetitors\""));
        assert!(output.contains("\"VerifyUser\""));
        assert!(output.contains("process.stdout.write(JSON.stringify(workflows)"));
        assert!(output.contains("process.exit(0)"));
    }

    #[test]
    fn no_workflows_produces_valid_ts() {
        let doc = Document {
            imports: Vec::new(),
            types: Vec::new(),
            clients: Vec::new(),
            tools: Vec::new(),
            agents: Vec::new(),
            workflows: Vec::new(),
            listeners: Vec::new(),
            tests: Vec::new(),
            mocks: Vec::new(),
            synthesizers: Vec::new(),
            span: 0..0,
        };
        let output = generate_ts(&doc).unwrap();
        // Empty workflow list
        assert!(output.contains("const workflows = [\n\n    ]") || output.contains("workflows = ["));
        // No agent runners
        assert!(!output.contains("runAgent_"));
        // No exported workflow functions
        assert!(!output.contains("export async function"));
    }

    fn valid_document() -> Document {
        Document {
            imports: Vec::new(),
            types: vec![
                TypeDecl {
                    name: "SearchResult".to_owned(),
                    fields: vec![
                        TypeField {
                            name: "url".to_owned(),
                            data_type: DataType::String(10..16),
                            constraints: Vec::new(),
                            span: 10..23,
                        },
                        TypeField {
                            name: "confidence_score".to_owned(),
                            data_type: DataType::Float(24..29),
                            constraints: vec![Constraint {
                                name: "min".to_owned(),
                                value: spanned(Expr::IntLiteral(0), 30..37),
                                span: 30..37,
                            }],
                            span: 24..37,
                        },
                        TypeField {
                            name: "snippet".to_owned(),
                            data_type: DataType::String(38..44),
                            constraints: Vec::new(),
                            span: 38..52,
                        },
                        TypeField {
                            name: "tags".to_owned(),
                            data_type: DataType::List(
                                Box::new(DataType::String(58..64)),
                                53..65,
                            ),
                            constraints: Vec::new(),
                            span: 53..65,
                        },
                    ],
                    span: 0..65,
                },
                TypeDecl {
                    name: "VerifiedUser".to_owned(),
                    fields: vec![
                        TypeField {
                            name: "email".to_owned(),
                            data_type: DataType::String(70..76),
                            constraints: vec![Constraint {
                                name: "regex".to_owned(),
                                value: spanned(
                                    Expr::StringLiteral(
                                        "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$".to_owned(),
                                    ),
                                    77..125,
                                ),
                                span: 77..125,
                            }],
                            span: 70..125,
                        },
                        TypeField {
                            name: "age".to_owned(),
                            data_type: DataType::Int(126..129),
                            constraints: vec![Constraint {
                                name: "min".to_owned(),
                                value: spanned(Expr::IntLiteral(18), 130..138),
                                span: 130..138,
                            }],
                            span: 126..138,
                        },
                    ],
                    span: 66..138,
                },
            ],
            clients: vec![ClientDecl {
                name: "FastOpenAI".to_owned(),
                provider: "openai".to_owned(),
                model: "gpt-5.1".to_owned(),
                retries: Some(2),
                timeout_ms: Some(5_000),
                endpoint: None,
                api_key: None,
                span: 139..165,
            }],
            tools: vec![ToolDecl {
                name: "WebSearch".to_owned(),
                arguments: vec![TypeField {
                    name: "query".to_owned(),
                    data_type: DataType::String(166..172),
                    constraints: Vec::new(),
                    span: 166..180,
                }],
                return_type: Some(DataType::Custom("SearchResult".to_owned(), 181..193)),
                invoke_path: Some(
                    "module(\"scripts/search\").function(\"run\")".to_owned(),
                ),
                using: None,
                synthesizer: None,
                test_block: None,
                secrets: vec![],
                span: 166..220,
            }],
            agents: vec![AgentDecl {
                name: "Researcher".to_owned(),
                extends: None,
                client: Some("FastOpenAI".to_owned()),
                system_prompt: Some("Stay deterministic.".to_owned()),
                tools: vec!["WebSearch".to_owned()],
                dynamic_reasoning: std::cell::Cell::new(false),
                settings: AgentSettings {
                    entries: vec![
                        AgentSetting {
                            name: "max_steps".to_owned(),
                            value: SettingValue::Int(5),
                            span: 221..233,
                        },
                        AgentSetting {
                            name: "temperature".to_owned(),
                            value: SettingValue::Float(0.1),
                            span: 234..250,
                        },
                    ],
                    span: 221..250,
                },
                span: 221..280,
            }],
            workflows: vec![
                WorkflowDecl {
                    name: "AnalyzeCompetitors".to_owned(),
                    arguments: vec![TypeField {
                        name: "company".to_owned(),
                        data_type: DataType::String(281..287),
                        constraints: Vec::new(),
                        span: 281..295,
                    }],
                    return_type: Some(DataType::Custom("SearchResult".to_owned(), 296..308)),
                    artifact: None,
                    body: Block {
                        statements: vec![
                            Statement::LetDecl {
                                name: "report".to_owned(),
                                explicit_type: Some(DataType::Custom(
                                    "SearchResult".to_owned(),
                                    309..321,
                                )),
                                value: spanned(
                                    Expr::ExecuteRun {
                                        agent_name: "Researcher".to_owned(),
                                        kwargs: vec![(
                                            "task".to_owned(),
                                            spanned(
                                                Expr::Identifier("company".to_owned()),
                                                335..342,
                                            ),
                                        )],
                                        require_type: Some(DataType::Custom(
                                            "SearchResult".to_owned(),
                                            322..334,
                                        )),
                                    },
                                    309..360,
                                ),
                                span: 309..360,
                            },
                            Statement::Return {
                                value: spanned(
                                    Expr::Identifier("report".to_owned()),
                                    361..374,
                                ),
                                span: 361..374,
                            },
                        ],
                        span: 309..374,
                    },
                    span: 281..374,
                },
                WorkflowDecl {
                    name: "VerifyUser".to_owned(),
                    arguments: vec![TypeField {
                        name: "email".to_owned(),
                        data_type: DataType::String(375..381),
                        constraints: Vec::new(),
                        span: 375..387,
                    }],
                    return_type: Some(DataType::Custom("VerifiedUser".to_owned(), 388..400)),
                    artifact: None,
                    body: Block {
                        statements: vec![
                            Statement::LetDecl {
                                name: "user".to_owned(),
                                explicit_type: Some(DataType::Custom(
                                    "VerifiedUser".to_owned(),
                                    401..413,
                                )),
                                value: spanned(
                                    Expr::ExecuteRun {
                                        agent_name: "Researcher".to_owned(),
                                        kwargs: vec![(
                                            "task".to_owned(),
                                            spanned(
                                                Expr::Identifier("email".to_owned()),
                                                427..432,
                                            ),
                                        )],
                                        require_type: Some(DataType::Custom(
                                            "VerifiedUser".to_owned(),
                                            414..426,
                                        )),
                                    },
                                    401..452,
                                ),
                                span: 401..452,
                            },
                            Statement::Return {
                                value: spanned(
                                    Expr::Identifier("user".to_owned()),
                                    453..464,
                                ),
                                span: 453..464,
                            },
                        ],
                        span: 401..464,
                    },
                    span: 375..464,
                },
            ],
            listeners: Vec::new(),
            tests: Vec::new(),
            mocks: Vec::new(),
            synthesizers: Vec::new(),
            span: 0..464,
        }
    }
}
